from __future__ import annotations

from collections.abc import Iterable

from backend.app.models.v5_plugin import V5PluginManifest


CATEGORIES = (
    "workload", "transaction_admission", "txpool", "sharding", "routing",
    "block_producer", "consensus", "network", "execution", "scheduler",
    "block_executor", "state_access", "state_storage", "cross_shard", "commit", "fault_injection",
    "metrics", "observability",
)


def _schema(properties: dict) -> dict:
    return {"type": "object", "properties": properties}


_ZH = {
    "deterministic_signed_synthetic": ("确定性签名合成负载", "生成带签名的确定性片内、跨片及超时退款交易。"),
    "signature_nonce_admission": ("签名与随机数准入", "校验 Ed25519 签名、发送方公钥绑定和随机数。"),
    "metatrack_strict_admission_v1": ("MetaTrack 严格访问声明准入", "在签名校验基础上要求结构化访问声明完整、状态键唯一且访问模式明确。"),
    "fifo_per_node_mempool": ("每节点 FIFO 交易池", "每个节点维护独立的 FIFO 交易池。"),
    "deterministic_state_key_sharding": ("确定性状态键分片", "将账户和状态键映射到配置的分片。"),
    "hash_routing_baseline": ("有状态哈希路由参考", "按源分片执行并使用本地状态的历史参考路由。"),
    "stateless_hash_routing": ("无状态哈希路由基线", "使用确定性状态归属、远程状态获取与写回的公平无状态哈希路由。"),
    "porygon_stateless_routing": ("Porygon 单排序域路由", "所有交易进入同一物理 PBFT 排序域，逻辑执行分片由 Porygon ESC 计划完成。"),
    "porygon_transaction_block_producer": ("Porygon 交易块装配器", "构造带交易根、签名访问根和完整数据可用性证据的 Transaction Block。"),
    "porygon_execution": ("Porygon 执行分类", "全局排序后按发送方身份确定逻辑执行子委员会。"),
    "porygon_pipeline_scheduler": ("Porygon 三维并行规划器", "构造 W/O/E/C 协议槽、Cross-Batch Witness、逻辑 ESC 分配、状态锁和跨片单次执行计划。"),
    "porygon_block_executor": ("Porygon 逻辑分片执行器", "按共识绑定的逻辑 ESC/wave 计划并行执行，并在单排序域内原子物化多状态更新。"),
    "porygon_remote_state_access": ("Porygon 签名访问投影", "每笔执行仅可见签名 AccessList 声明状态；不复用 MetaTrack 远程 CAS 控制面。"),
    "calvin_global_routing": ("Calvin 全局排序路由", "Calvin 有状态基线：所有交易进入统一 PBFT 排序域，状态仍按执行分区持有。"),
    "stateless_calvin_global_routing": ("Stateless Calvin 全局排序路由", "Calvin 无状态适配：统一 PBFT 排序域，不激活 MetaTrack 路由控制面。"),
    "calvin_declared_access_admission": ("Calvin 静态访问声明准入", "要求签名 AccessList 完整且仅包含确定读写模式。"),
    "calvin_execution": ("Calvin 确定性执行", "按照共识确定的全局事务顺序执行。"),
    "calvin_deterministic_scheduler": ("Calvin 确定性锁调度", "每键 FIFO 共享/排他锁、等待计数与 Ready Queue。"),
    "calvin_block_executor": ("Calvin 区块执行器", "有状态分区 Calvin：READ_RESULT + 本地写入 + 无冲突回滚。"),
    "stateless_calvin_block_executor": ("Stateless Calvin 区块执行器", "使用签名 AccessList 状态投影的 Calvin 兼容适配。"),
    "calvin_partition_state_access": ("Calvin 分区状态访问", "常驻分区状态与 READ_RESULT 读取转发。"),
    "stateless_calvin_state_access": ("Stateless Calvin 状态访问", "仅向执行器暴露声明状态投影。"),
    "calvin_partition_state_store": ("Calvin 分区状态存储", "按 ExecutionShardID 隔离的持久状态与证据存储。"),
    "calvin_no_2pc_coordinator": ("Calvin 无 2PC 协调", "关闭 MBE Relay/Finalize；跨分区依赖由 Calvin READ_RESULT 与确定性锁处理。"),
    "porygon_cross_shard_coordinator": ("Porygon 逻辑跨片协调", "记录状态锁、Single-Shard Execution 与 Multi-Shard Update；不触发 MBE 物理 Relay。"),
    "metatrack_coaccess_routing": ("MetaTrack 共访存路由", "按批次访问频率与状态共现构造有容量约束的执行侧状态放置，并以 MajorityPlace 决定交易执行分片。"),
    "time_or_count_block_producer": ("时间或数量出块器", "Leader 按时间间隔或交易池数量持续提议区块。"),
    "aria_block_producer": ("Aria 批次区块装配器", "按同一状态快照执行一个 Aria 批次，将可提交交易组装入当前区块，并将冲突交易按原顺序留到后续区块。"),
    "groundhog_block_producer": ("Groundhog 区块装配器", "基于同一快照解释候选交易并通过类型化状态预留筛选可共同成立的区块交易。"),
    "pbft_style_consensus": ("PBFT 风格共识", "基于本地 TCP 的 PrePrepare、Prepare 和 Commit 法定人数消息流程。"),
    "localhost_tcp_typed_network": ("本地 TCP 类型化网络", "在独立 localhost TCP 监听器上传输类型化消息。"),
    "serial_execution_baseline": ("串行执行基线", "确定性的串行执行基线。"),
    "batch_si_execution": ("Batch-SI 执行分类器", "仅为 Batch-SI 提供独立的执行轨分类，不调用其他方案算法代码。"),
    "dual_track_execution": ("双轨执行", "记录快速轨与保守轨执行证据的确定性执行插件。"),
    "fifo_serial_scheduler": ("FIFO 串行调度器", "对已准入交易进行 FIFO 调度。"),
    "fast_first_scheduler": ("快速优先调度器", "用于双轨执行的快速优先调度器。"),
    "dependency_influence_scheduler": ("依赖关键交易优先调度器", "仅在依赖与 StateReady 已满足的交易之间，按后向依赖深度 H、后继数量 D、规范顺序依次优先。"),
    "ready_round_control_scheduler": ("就绪轮次对照调度器", "与依赖关键交易优先使用相同的就绪轮次与统一 Worker 模型，但轮次内保持快速轨优先并按规范顺序仲裁。"),
    "batch_si_scheduler": ("Batch-SI 批次规划器", "在共识前独立执行 AWRT、WRBP 与 OFAS，并将确定性批次计划绑定到区块。"),
    "batch_si_block_executor": ("Batch-SI 批快照执行器", "按批次顺序、批内统一快照并行执行 Batch-SI 计划，不调用其他方案算法代码。"),
    "fabricpp_cg_execution": ("Fabric++ CG 执行分类", "Sharma 等 SIGMOD 2019 Fabric++ 传统冲突图执行分类。"),
    "fabricpp_cg_scheduler": ("Fabric++ CG 事务重排序", "按 WS(Ti)∩RS(Tj) 构造冲突图，Tarjan+Johnson 精确枚举周期并按最大周期参与度确定性移除事务，生成可串行化调度。"),
    "fabricpp_cg_block_executor": ("Fabric++ CG 区块执行器", "执行 Fabric++ 消环后的可串行化调度，并将 Algorithm 1 移除事务记录为确定性终态失败空操作。"),
    "cg_execution": ("CG / Nezha 执行分类", "Nezha 传统 CG：官方冲突多重图；可枚举区域使用完整 JohnsonCE，超预算区域使用确定性 Johnson 前缀消环；victim 延后重试。"),
    "cg_scheduler": ("CG / Nezha 冲突图调度", "按官方 NewBuildConflictGraph 保留 WW 重复弧；Tarjan + JohnsonCE/BreakCycles，超预算时以确定性 Johnson 前缀继续相同 victim 规则，并将 victim 延后重试。"),
    "cg_block_executor": ("CG / Nezha MBE Worker 执行器", "只执行当前 accepted CG frontiers；cycle victim 不生成终态失败回执，而是返回 FIFO mempool 后续重试。"),
    "acg_execution": ("ACG / Nezha 执行分类", "Nezha 地址冲突图与层次排序；HS 中止由 MBE 生命周期延后重试。"),
    "acg_scheduler": ("ACG / Nezha 地址冲突图调度", "CreateGraph → QueuesSort → DeSS 保持不变，HS victim 通过 Deferred 留待后续区块。"),
    "acg_block_executor": ("ACG / Nezha 并行执行器", "只执行当前区块 accepted HS waves；deferred victim 不在本块生成终态失败回执。"),
    "bsx_execution": ("BSX 执行分类", "论文对照组：无向冲突图着色调度。"),
    "bsx_scheduler": ("BSX 图着色调度", "构造无向冲突图并使用确定性 DSATUR 启发式着色。"),
    "bsx_block_executor": ("BSX 并行执行器", "同色无冲突事务并行、颜色批次顺序推进。"),
    "aria_block_executor": ("Aria 批量乐观执行器", "验证固定 Aria 批次在同一快照、读写预留与 Rule 2 下可以单纪元提交。"),
    "groundhog_block_executor": ("Groundhog 无序区块执行器", "对固定区块执行同快照类型化修改验证、约束合并和确定性状态物化。"),
    "direct_state_access": ("直接状态访问", "直接访问确定性状态数据库。"),
    "persistent_local_state_store": ("本地持久化状态存储", "每个节点持久化状态、区块、回执和交易索引。"),
    "relay_certificate_protocol": ("中继证书跨片协议", "提供 SourceLock、中继证书、TargetCommit、SourceFinalize 与超时退款证据。"),
    "normal_commit": ("普通提交", "确定性的持久化提交。"),
    "commutative_hot_update_aggregation": ("可交换热点更新聚合", "记录热点更新聚合决策的提交配置。"),
    "faults_disabled": ("禁用故障注入", "不施加网络故障策略。"),
    "network_delay_drop": ("网络延迟与丢包", "确定性的真实 TCP 延迟和丢包策略。"),
    "runtime_core_metrics": ("运行时核心指标", "运行时计数器和状态根汇总。"),
    "node_network_consensus_observer": ("节点网络共识观测器", "生成节点、TCP、共识日志和产物目录。"),
}


def _manifest(category: str, plugin_id: str, display_name: str, description: str, *,
              config: dict | None = None, schema: dict | None = None, capabilities: list[str] | None = None,
              requirements: list[str] | None = None, metrics: list[dict] | None = None,
              aliases: list[str] | None = None, supported_backends: list[str] | None = None,
              truth_boundary: str = "v5_real_cluster_candidate", source: dict | None = None) -> V5PluginManifest:
    display_name_zh, description_zh = _ZH.get(plugin_id, (display_name, description))
    return V5PluginManifest(
        plugin_id=plugin_id, category=category, display_name=display_name, description=description,
        display_name_zh=display_name_zh, description_zh=description_zh,
        supported_backends=supported_backends or ["preview", "simulation", "real_cluster"],
        config_schema=schema or _schema({}), default_config=config or {}, capabilities=capabilities or [],
        requirements=requirements or [], metrics=metrics or [], runtime_factory=f"builtin:{plugin_id}",
        runtime_adapter="go_factory_registry", truth_boundary=truth_boundary, source=source or {}, legacy_aliases=aliases or [],
    )


_MANIFESTS = [
    _manifest("workload", "deterministic_signed_synthetic", "Deterministic Signed Synthetic", "Deterministic signed workload with intra-shard, relay, and timeout cases.", config={"cross_shard_ratio": 0.25, "timeout_every": 17}, schema=_schema({"cross_shard_ratio": {"type": "number", "minimum": 0, "maximum": 1, "default": 0.25}, "timeout_every": {"type": "integer", "minimum": 0, "maximum": 1000, "default": 17}}), metrics=[{"key": "submitted_tx_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions submitted over TCP."}]),
    _manifest("workload", "canonical_trace_replay", "Canonical Trace Replay", "Streams deterministic materialized dataset workload records through a manifest-owned universal access-list contract.", config={}, schema=_schema({"dataset_id": {"type": "string"}, "variant_mode": {"type": "string"}, "selection_mode": {"type": "string", "enum": ["contiguous_window", "validated_prefix"]}, "skew_axis": {"type": ["string", "null"]}, "target_alpha": {"type": ["number", "null"]}, "variant_parameters": {"type": "object"}}), capabilities=["dataset_replay", "gzip_streaming", "manifest_variants", "direct_access_list_v3", "no_fallback"], metrics=[{"key": "workload_replay_read_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Canonical workload records read by the client."}]),
    _manifest("transaction_admission", "signature_nonce_admission", "Signature and Nonce Admission", "Ed25519 signature, sender/public-key binding, and nonce admission.", capabilities=["signed_tx", "nonce_validation"]),
    _manifest("transaction_admission", "metatrack_strict_admission_v1", "MetaTrack Strict Access Admission", "MetaTrack-only signature admission with mandatory structured access declarations.", capabilities=["signed_tx", "nonce_validation", "declared_access_required"]),
    _manifest("txpool", "fifo_per_node_mempool", "FIFO Per-node Mempool", "Independent FIFO mempool on every node.", config={"capacity": 10000}, schema=_schema({"capacity": {"type": "integer", "minimum": 100, "maximum": 100000, "default": 10000}})),
    _manifest("sharding", "deterministic_state_key_sharding", "Deterministic State-key Sharding", "Maps account/state keys to a configured shard.", capabilities=["multi_shard"]),
    _manifest("routing", "hash_routing_baseline", "Stateful Hash Routing Reference", "Historical source-shard execution reference with local state access.", aliases=["hash"], capabilities=["stateful_local_execution"], truth_boundary="stateful_reference_not_directly_comparable_to_stateless_methods", metrics=[{"key": "routing_decision_count", "type": "integer", "unit": "decision", "aggregation": "sum", "visualization": "summary", "description": "Routing decisions made by the client."}]),
    _manifest("routing", "stateless_hash_routing", "Stateless Hash Routing Baseline", "Fair stateless hash baseline with deterministic state homes, exact per-key logical-version fetch for non-commutative business state, and home-shard writeback.", aliases=["stateless_hash"], capabilities=["batch_routing", "stateless_direct_execution", "remote_state_fetch", "remote_state_writeback", "exact_state_version_fetch", "per_key_version_writeback_frontier"], truth_boundary="stateless_hash_remote_home_exact_version_v2", metrics=[{"key": "routing_decision_count", "type": "integer", "unit": "decision", "aggregation": "sum", "visualization": "summary", "description": "Stateless hash routing decisions made by the client."}]),
    _manifest(
        "routing", "metatrack_coaccess_routing", "MetaTrack Co-access Routing",
        "Batch-level execution sharding from state access frequency and co-access weights, with an explicit admissible state-load capacity and MajorityPlace transaction routing.",
        config={"routing_epoch": 0},
        schema=_schema({
            "routing_epoch": {"type": "integer", "minimum": 0, "maximum": 1000000000, "default": 0},
            "control_policy": {"type": "string", "enum": ["legacy_v2", "logical_domain_frontier_v1", "declared_access_frontier_v2"], "default": "legacy_v2"},
            "logical_domain_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4},
            "state_storage_unit_count": {"type": "integer", "minimum": 0, "maximum": 65536, "default": 0},
            "micro_batch_size": {"type": "integer", "minimum": 0, "maximum": 5000, "default": 0},
            "placement_mu": {"type": "number", "minimum": 0.01, "maximum": 64.0, "default": 1.0},
            "placement_min_budget": {"type": "integer", "minimum": 1, "maximum": 1000000, "default": 1},
        }),
        aliases=["co_access", "metatrack"],
        capabilities=["batch_routing", "batch_frequency_coaccess", "admissible_state_load_capacity", "per_seed_top_cooccur_budget", "majority_place_queue_tie", "routing_epoch_evidence", "predicted_remote_access_accounting", "stateless_direct_execution", "remote_state_fetch", "remote_state_writeback", "exact_state_version_fetch", "logical_state_storage_units", "state_unit_execution_role_separation", "configurable_placement_budget", "configurable_micro_batch_size"],
        truth_boundary="metatrack_batch_execution_sharding_admissible_capacity_v2",
        source={"source_type": "user_manuscript_algorithm_reimplementation", "source_name": "MetaTrack batch-level execution sharding"},
        metrics=[{"key": "metatrack_routed_tx_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions routed through the MetaTrack profile."}],
    ),
    _manifest("block_producer", "time_or_count_block_producer", "Time or Count Block Producer", "Leader proposes blocks repeatedly by interval or mempool count; under MetaTrack routing it packs multiple complete signed route-batch projections into one pre-consensus proposal without splitting a projection.", config={"block_size": 100, "interval_ms": 75}, schema=_schema({"block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75}}), capabilities=["time_or_count_cut", "metatrack_complete_projection_preconsensus_aggregation"]),
    _manifest(
        "block_producer", "aria_block_producer", "Aria Block Producer",
        "Executes one deterministic Aria batch over the block-start snapshot, selects Rule-2-committable transactions for the current block, and releases deferred transactions back to FIFO mempool order for a later block.",
        config={
            "block_size": 100,
            "interval_ms": 75,
            "candidate_scan_multiplier": 1,
            "reordering": True,
            "read_only_optimization": True,
            "retry_nonce_gaps": True,
        },
        schema=_schema({
            "block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100},
            "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75},
            "candidate_scan_multiplier": {"type": "integer", "minimum": 1, "maximum": 32, "default": 1},
            "reordering": {"type": "boolean", "default": True},
            "read_only_optimization": {"type": "boolean", "default": True},
            "retry_nonce_gaps": {"type": "boolean", "default": True},
        }),
        capabilities=["aria_single_batch_assembly", "same_snapshot_execution", "rule2_conflict_selection", "fifo_deferred_transactions", "proposal_selection_evidence"],
        requirements=["block_executor:aria_block_executor", "routing:hash_routing_baseline", "execution:serial_execution_baseline", "scheduler:fifo_serial_scheduler", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="aria_rule2_one_consensus_block_per_batch_fallback_disabled",
        source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Aria: A Fast and Practical Deterministic OLTP Database", "doi": "10.14778/3407790.3407808", "source_repository": "https://github.com/luyi0619/aria", "source_commit": "d0508c393ec084582c12e6f3abadab63501eaedd", "reproduction_dossier": "docs/reproductions/aria/source_lock.md"},
    ),
    _manifest(
        "block_producer", "groundhog_block_producer", "Groundhog Block Producer",
        "Builds a Groundhog candidate by interpreting a wider FIFO candidate window against one block-start snapshot, reserving typed modifications, deferring only aggregate constraint conflicts, and preserving terminal application failures for final receipts.",
        config={"block_size": 100, "interval_ms": 75, "candidate_scan_multiplier": 4, "ordered_set_limit": 64},
        schema=_schema({
            "block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100},
            "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75},
            "candidate_scan_multiplier": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4},
            "ordered_set_limit": {"type": "integer", "minimum": 1, "maximum": 65535, "default": 64},
        }),
        capabilities=["groundhog_block_assembly", "same_snapshot_candidate_interpretation", "typed_state_reservation", "transaction_atomic_rollback", "constraint_conflict_deferral"],
        requirements=["block_executor:groundhog_block_executor", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store"],
        supported_backends=["real_cluster"],
        truth_boundary="groundhog_deterministic_candidate_assembly_over_concurrent_typed_reservation_validation;official_cpp_mempool_worker_race_not_reproduced",
        source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Groundhog: Linearly-Scalable Smart Contracting via Commutative Transaction Semantics", "arxiv": "2404.03201", "source_repository": "https://github.com/scslab/smart-contract-scalability", "source_commit": "6b357bc206b73ece39fd61fe7dba655352200c0a", "reproduction_dossier": "docs/reproductions/groundhog/source_lock.md"},
    ),
    _manifest("consensus", "pbft_style_consensus", "PBFT-style Consensus", "Local TCP PBFT-style PrePrepare, Prepare, and Commit quorum runtime.", capabilities=["pbft_messages", "quorum_commit"]),
    _manifest("network", "localhost_tcp_typed_network", "Localhost TCP Typed Network", "Typed message transport on distinct localhost TCP listeners.", capabilities=["tcp", "typed_messages"]),
    _manifest("execution", "serial_execution_baseline", "Serial Execution", "Deterministic serial execution baseline."),
    _manifest(
        "execution", "batch_si_execution", "Batch-SI Execution Classifier",
        "Private Batch-SI execution-track classifier. It only identifies transactions for the Batch-SI planner and does not reuse another scheme's algorithm implementation.",
        capabilities=["batch_si_execution_track", "no_cross_scheme_algorithm_reuse"],
        supported_backends=["real_cluster"],
        truth_boundary="batch_si_private_execution_classification_contract",
        source={"source_type": "paper_reimplementation", "source_name": "Batch-SI: Semi-Parallel Concurrency Scheme for Permissioned Blockchains Exploiting Batch Snapshot Isolation", "reproduction_dossier": "docs/reproductions/batch_si/source_lock.md"},
    ),
    _manifest(
        "execution", "dual_track_execution", "Dual-track Execution",
        "Deterministic fast/conservative admission driven by access stability, static dependency-frontier position, dependency-topology safety, and execution-semantic stability. Access-list size is diagnostic only and does not choose the track.",
        aliases=["dual_track"],
        capabilities=["dual_track", "access_stability_admission", "dependency_frontier_fast_root", "dependency_frontier_conservative_nonroot", "semantic_stability_admission", "state_ready_orthogonal_to_track", "nontrivial_scc_conservative_fallback"],
        truth_boundary="metatrack_dual_track_dependency_frontier_v2",
    ),
    _manifest("scheduler", "fifo_serial_scheduler", "FIFO Serial Scheduler", "FIFO scheduler for admitted transactions."),
    _manifest("scheduler", "fast_first_scheduler", "Fast-first Scheduler", "Fast-first scheduler for dual-track execution.", requirements=["execution:dual_track_execution"]),
    _manifest("scheduler", "dependency_influence_scheduler", "Dependency-influence Scheduler", "Among already-ready MetaTrack transactions, prioritizes larger tail depth H, then larger descendant count D, then canonical routing ordinal.", requirements=["execution:dual_track_execution"], capabilities=["metatrack_dependency_influence_priority"], source={"type": "mbe_mechanism_candidate", "evidence": "metatrack_dependency_structure_v33"}),
    _manifest("scheduler", "ready_round_control_scheduler", "Ready-round Control Scheduler", "Uses non-waiting Ready Rounds and the same unified worker-lane model as the dependency-influence candidate, but preserves fast-first then canonical ordering within the oldest round.", requirements=["execution:dual_track_execution"], capabilities=["metatrack_ready_round_arbitration", "bounded_cross_round_bypass"]),
    _manifest(
        "scheduler", "batch_si_scheduler", "Batch-SI Batch Planner",
        "Independently constructs AWRT, applies WRBP, performs OFAS, defers cyclic transactions before consensus, and commits a deterministic batch plan to the block.",
        config={"partition_mode": "wrbp", "ordering_mode": "ofas", "priority_mode": "paper"},
        schema=_schema({
            "partition_mode": {"type": "string", "enum": ["wrbp", "sequential"], "default": "wrbp"},
            "ordering_mode": {"type": "string", "enum": ["ofas", "dependency_graph"], "default": "ofas"},
            "priority_mode": {"type": "string", "enum": ["paper", "txid"], "default": "paper"},
        }),
        capabilities=["batch_si", "awrt", "wrbp", "ofas", "pre_consensus_execution_plan", "deterministic_deferral"],
        requirements=["block_executor:batch_si_block_executor", "execution:batch_si_execution", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="batch_si_ordering_reimplementation_over_declared_mbe_access_lists",
        source={"source_type": "paper_reimplementation", "source_name": "Batch-SI: Semi-Parallel Concurrency Scheme for Permissioned Blockchains Exploiting Batch Snapshot Isolation", "reproduction_dossier": "docs/reproductions/batch_si/source_lock.md"},
    ),
    _manifest(
        "block_executor", "serial_block_executor", "Serial Block Executor",
        "Executes block transactions in original order through the generic block executor contract.",
        config={"worker_count": 1},
        schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 1, "default": 1, "readOnly": True}}),
        capabilities=["serial_order", "deterministic_state_delta", "legacy_equivalence_oracle", "execution_plan_digest"],
        metrics=[
            {"key": "block_executor_id", "type": "string", "unit": "", "aggregation": "last", "visualization": "summary", "description": "Selected block executor plugin."},
            {"key": "block_execution_ms", "type": "number", "unit": "ms", "aggregation": "sum", "visualization": "summary", "description": "Block execution wall-clock time."},
            {"key": "executed_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions executed by the block executor."},
            {"key": "execution_plan_digest", "type": "string", "unit": "", "aggregation": "last", "visualization": "summary", "description": "Deterministic execution plan digest."},
            {"key": "plan_digest_consistent", "type": "ratio", "unit": "boolean", "aggregation": "all", "visualization": "summary", "description": "Committed nodes agree on plan digest evidence."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="legacy_faithful_reference_baseline",
        source={"source_type": "internal_reference", "source_name": "MBE legacy realism serial execution engine", "source_commit": "84f28f43f2cfe93864fd4e4b68377fcfd31a5595", "reproduction_dossier": "docs/reproductions/serial/source_lock.md"},
    ),
    _manifest(
        "block_executor", "metatrack_block_executor", "MetaTrack Block Executor",
        "Executes MetaTrack fast/conservative ready queues with dependency and transaction-level remote StateReady suspend/resume callbacks over MBE transfer semantics.",
        config={"worker_count": 4},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 8, "default": 4},
            "control_policy": {"type": "string", "enum": ["logical_domain_frontier_v1", "declared_access_frontier_v2"]},
        }),
        capabilities=["metatrack_ready_queues", "dependency_release", "transaction_level_remote_state_ready", "state_wait_suspend_resume", "deterministic_state_delta", "execution_plan_digest"],
        requirements=["execution:dual_track_execution"],
        metrics=[
            {"key": "fast_track_execution_instance_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Fast-track execution instances completed by MetaTrack."},
            {"key": "blocked_queue_max_depth", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum planned/actual dependency queue depth."},
            {"key": "wakeup_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "Dependency releases that moved transactions into ready queues."},
            {"key": "state_wait_blocked_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "Transactions suspended because one or more required remote state keys were not StateReady."},
            {"key": "state_ready_wakeup_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "StateReady arrivals that woke a suspended transaction."},
            {"key": "remote_state_fetch_completed_count", "type": "integer", "unit": "fetch", "aggregation": "sum", "visualization": "summary", "description": "Remote state fetches completed by transaction-level StateReady scheduling."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="metatrack_native_transaction_level_state_ready_suspend_resume",
    ),
    _manifest(
        "block_executor", "aria_block_executor", "Aria Block Executor",
        "Validates a fixed one-epoch Aria batch over the block-start snapshot using minimum-TID read/write reservations, Rule 2 deterministic reordering, and no serial or Calvin fallback.",
        config={
            "worker_count": 4,
            "reordering": True,
            "read_only_optimization": True,
            "retry_nonce_gaps": True,
        },
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4},
            "reordering": {"type": "boolean", "default": True},
            "read_only_optimization": {"type": "boolean", "default": True},
            "retry_nonce_gaps": {"type": "boolean", "default": True},
        }),
        capabilities=[
            "aria", "deterministic_batch_occ", "same_snapshot_epoch",
            "read_write_reservation", "deterministic_reordering_rule2",
            "single_epoch_fixed_block_validation", "execution_plan_digest",
        ],
        requirements=["block_producer:aria_block_producer", "routing:hash_routing_baseline", "execution:serial_execution_baseline", "scheduler:fifo_serial_scheduler", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        metrics=[
            {"key": "aria_epoch_count", "type": "integer", "unit": "epoch", "aggregation": "sum", "visualization": "summary", "description": "Aria execution/commit epochs completed; fixed blocks must report exactly one."},
            {"key": "aria_conflict_abort_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Conflict attempts rejected during fixed-block validation; expected to be zero."},
            {"key": "aria_candidate_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions inspected by the proposer-side Aria batch selection."},
            {"key": "aria_selected_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Rule-2-committable transactions selected into the consensus block."},
            {"key": "aria_deferred_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions retained in FIFO mempool order for a later block."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed concurrent Aria execution width."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="aria_rule2_one_consensus_block_per_batch_fallback_disabled",
        source={
            "source_type": "paper_and_official_source_reimplementation",
            "source_name": "Aria: A Fast and Practical Deterministic OLTP Database",
            "doi": "10.14778/3407790.3407808",
            "source_repository": "https://github.com/luyi0619/aria",
            "source_commit": "d0508c393ec084582c12e6f3abadab63501eaedd",
            "reproduction_dossier": "docs/reproductions/aria/source_lock.md",
        },
    ),
    _manifest(
        "block_executor", "groundhog_block_executor", "Groundhog Block Executor",
        "Reimplements Groundhog unordered-block execution over MBE transaction semantics using one block-start snapshot, typed commutative modifications, reserve/rollback validation, deterministic materialization, and no serial fallback.",
        config={"worker_count": 4, "ordered_set_limit": 64},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4},
            "ordered_set_limit": {"type": "integer", "minimum": 1, "maximum": 65535, "default": 64},
        }),
        capabilities=["groundhog", "unordered_block", "block_start_snapshot", "typed_commutative_modifications", "nonnegative_int64_set_add", "bytes_set", "ordered_set", "concurrent_reserve_commit_rollback", "transactional_reservation_rewind", "deterministic_materialization", "no_serial_fallback", "execution_plan_digest"],
        requirements=["block_producer:groundhog_block_producer", "routing:hash_routing_baseline", "execution:serial_execution_baseline", "scheduler:fifo_serial_scheduler", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        metrics=[
            {"key": "groundhog_execution_attempt_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Groundhog transaction interpretations against the common block snapshot."},
            {"key": "groundhog_reservation_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Typed modifications successfully reserved."},
            {"key": "groundhog_constraint_conflict_count", "type": "integer", "unit": "conflict", "aggregation": "sum", "visualization": "summary", "description": "Typed-state constraints that rejected a transaction or fixed block."},
            {"key": "groundhog_reservation_rollback_count", "type": "integer", "unit": "rollback", "aggregation": "sum", "visualization": "summary", "description": "Transaction-level reservation rollbacks."},
            {"key": "groundhog_integer_merge_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Nonnegative integer set-add modifications merged."},
            {"key": "groundhog_bytes_merge_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Byte-string set modifications merged."},
            {"key": "groundhog_ordered_set_merge_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Ordered-set insert, clear, and limit modifications merged."},
            {"key": "groundhog_modified_key_count", "type": "integer", "unit": "key", "aggregation": "sum", "visualization": "summary", "description": "Distinct state keys materialized by Groundhog."},
            {"key": "groundhog_reservation_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum concurrent Groundhog reserve/revert/commit width over disjoint object reservations."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed concurrent Groundhog interpretation width."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="groundhog_supported_typed_state_semantics_with_concurrent_transactional_reserve_revert_commit;official_cpp_storage_engine_not_embedded",
        source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Groundhog: Linearly-Scalable Smart Contracting via Commutative Transaction Semantics", "arxiv": "2404.03201", "source_repository": "https://github.com/scslab/smart-contract-scalability", "source_commit": "6b357bc206b73ece39fd61fe7dba655352200c0a", "reproduction_dossier": "docs/reproductions/groundhog/source_lock.md"},
    ),
    _manifest(
        "block_executor", "block_stm_block_executor", "Block-STM Block Executor",
        "Reimplements the Block-STM speculative block execution mechanism over MBE transfer semantics with MVMemory, validation, abort, and deterministic ordered materialization.",
        config={"worker_count": 4, "maximum_incarnations": 0},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 8, "default": 4},
            "maximum_incarnations": {"type": "integer", "minimum": 0, "maximum": 1000000, "default": 0, "description": "0 disables the artificial per-transaction incarnation cap for formal experiments."},
        }),
        capabilities=["block_stm", "mvmemory", "speculative_execution", "captured_reads", "validation", "abort_reexecution", "estimate_dependency", "serial_equivalence"],
        requirements=["state_access:direct_state_access", "state_storage:persistent_local_state_store"],
        metrics=[
            {"key": "worker_count", "type": "integer", "unit": "worker", "aggregation": "last", "visualization": "summary", "description": "Configured Block-STM workers."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed Block-STM parallel width."},
            {"key": "abort_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Validation abort count."},
            {"key": "reexecution_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions re-executed after abort."},
            {"key": "dependency_wait_count", "type": "integer", "unit": "wait", "aggregation": "sum", "visualization": "summary", "description": "ESTIMATE/dependency waits."},
            {"key": "validation_failure_count", "type": "integer", "unit": "failure", "aggregation": "sum", "visualization": "summary", "description": "Read validation failures."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="block_stm_core_reimplementation_over_mbe_transaction_semantics",
        source={"source_type": "paper_and_source_reimplementation", "source_name": "Block-STM: Scaling Blockchain Execution by Turning Ordering Curse to a Performance Blessing", "arxiv": "2203.06871v3", "source_repository": "https://github.com/aptos-labs/aptos-core", "source_commit": "20f9379515358add43f4042693462aaedd654826", "reproduction_dossier": "docs/reproductions/block_stm/source_lock.md"},
    ),
    _manifest(
        "block_executor", "batch_si_block_executor", "Batch-SI Block Executor",
        "Executes the committed Batch-SI plan with sequential batches, one immutable snapshot per batch, parallel transactions inside a batch, and deterministic state materialization using Batch-SI-owned transaction semantics.",
        config={"worker_count": 4, "partition_mode": "wrbp", "ordering_mode": "ofas", "priority_mode": "paper", "execution_mode": "snapshot_parallel"},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4},
            "partition_mode": {"type": "string", "enum": ["wrbp", "sequential"], "default": "wrbp"},
            "ordering_mode": {"type": "string", "enum": ["ofas", "dependency_graph"], "default": "ofas"},
            "priority_mode": {"type": "string", "enum": ["paper", "txid"], "default": "paper"},
            "execution_mode": {"type": "string", "enum": ["snapshot_parallel", "snapshot_serial"], "default": "snapshot_parallel"},
        }),
        capabilities=["batch_si", "batch_snapshot_isolation", "sequential_batches", "intra_batch_parallelism", "deterministic_state_delta", "execution_plan_digest", "no_cross_scheme_algorithm_reuse"],
        requirements=["scheduler:batch_si_scheduler", "routing:hash_routing_baseline", "execution:batch_si_execution", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        metrics=[
            {"key": "configured_worker_count", "type": "integer", "unit": "worker", "aggregation": "last", "visualization": "summary", "description": "Configured Batch-SI intra-batch workers."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed intra-batch parallel width."},
            {"key": "batch_count", "type": "integer", "unit": "batch", "aggregation": "sum", "visualization": "summary", "description": "WRBP execution batches."},
            {"key": "maximum_batch_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Largest Batch-SI batch width."},
            {"key": "write_opportunity_reuse_count", "type": "integer", "unit": "opportunity", "aggregation": "sum", "visualization": "summary", "description": "WRBP write-opportunity batch assignments reused."},
            {"key": "dependency_edge_count", "type": "integer", "unit": "dependency", "aggregation": "sum", "visualization": "summary", "description": "Intra-batch read/write dependency edges inspected."},
            {"key": "deferred_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "OFAS cycle victims returned to the mempool before PBFT."},
            {"key": "batch_snapshot_create_ms", "type": "number", "unit": "ms", "aggregation": "sum", "visualization": "summary", "description": "Time spent creating immutable batch snapshots."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="batch_si_core_reimplementation_over_mbe_transaction_and_state_contracts",
        source={"source_type": "paper_reimplementation", "source_name": "Batch-SI: Semi-Parallel Concurrency Scheme for Permissioned Blockchains Exploiting Batch Snapshot Isolation", "reproduction_dossier": "docs/reproductions/batch_si/source_lock.md"},
    ),
    _manifest(
        "execution", "fabricpp_cg_execution", "Fabric++ Traditional CG Execution",
        "Sharma et al. SIGMOD 2019 transaction-reordering conflict-graph classifier using write-read conflicts only.",
        capabilities=["paper_baseline_fabricpp_cg", "fabricpp_read_write_conflict_definition", "tarjan_scc", "johnson_exact_cycle_enumeration", "deterministic_cycle_victim"],
        supported_backends=["real_cluster"],
        truth_boundary="fabricpp_sigmod2019_transaction_reordering_v1",
        source={"source_type": "paper_reimplementation", "source_name": "Blurring the Lines between Blockchains and Database Systems: the Case of Hyperledger Fabric", "venue": "SIGMOD 2019", "doi": "10.1145/3299869.3319883", "algorithm": "Algorithm 1 transaction reordering", "conflict_definition": "WS(Ti) intersect RS(Tj) nonempty", "reproduction_dossier": "docs/reproductions/fabricpp_cg/source_lock.md"},
    ),
    _manifest(
        "scheduler", "fabricpp_cg_scheduler", "Fabric++ Traditional CG Scheduler",
        "Builds the Fabric++ write-read conflict graph, divides it with Tarjan, enumerates all elementary cycles with Johnson, removes maximum-cycle-participation victims with lower original ordinal tie-break, and derives a serializable residual schedule.",
        capabilities=["consensus_bound_schedule", "fabricpp_read_write_conflict_definition", "no_standalone_ww_edges", "tarjan_scc", "johnson_exact_cycle_enumeration", "maximum_cycle_participation_abort", "lower_ordinal_tie_break", "serializable_schedule"],
        requirements=["execution:fabricpp_cg_execution", "block_executor:fabricpp_cg_block_executor", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="fabricpp_sigmod2019_transaction_reordering_v1",
    ),
    _manifest(
        "block_executor", "fabricpp_cg_block_executor", "Fabric++ Traditional CG Block Executor",
        "Serially materializes the consensus-bound Fabric++ Algorithm-1 order as an MBE adapter; Algorithm 1 cycle victims are terminal failed no-ops. No post-reordering parallel execution is added.",
        config={"worker_count": 1},
        schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 1, "default": 1, "readOnly": True}}),
        capabilities=["serial_paper_order_materialization", "deterministic_materialization", "fabricpp_cycle_abort_receipts", "no_cross_scheme_algorithm_reuse"],
        requirements=["execution:fabricpp_cg_execution", "scheduler:fabricpp_cg_scheduler", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="fabricpp_sigmod2019_transaction_reordering_v1",
    ),
_manifest("execution", "cg_execution", "CG / Nezha Execution", "Official-reference Nezha conventional CG classifier over the exact directed conflict multigraph.", capabilities=["paper_baseline_cg", "official_conflict_multigraph", "cycle_detection", "nezha_johnson_cycle_abort", "bounded_johnson_prefix_fallback", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_cg_official_multigraph_bounded_johnson_retry_mbe_worker_v4", source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Nezha: Exploiting Concurrency for Transaction Processing in DAG-based Blockchains", "doi": "10.1109/ICDCS54860.2022.00034", "official_repository": "CGCL-codes/Nezha", "official_commit": "85eaf541591e5f3020dd520cf3b8ee35009d296a", "reference_files": ["core/classical_graph.go", "graph/johnsonce.go", "graph/tarjanscc.go", "test.go"], "reference_scope": "conventional CG baseline shipped with the Nezha artifact", "cycle_resolution": "Tarjan SCC; complete JohnsonCE/BreakCycles while within the deterministic planning budget; if the exact cycle space exceeds that budget, MBE consumes the deterministic Johnson prefix with the same maximum-membership BreakCycles rule, removes those feedback victims, recomputes SCCs, and continues", "implementation_note": "WW parallel-arc multiplicity from NewBuildConflictGraph is preserved; bounded Johnson is an explicit scalability adaptation only for otherwise non-terminating cycle spaces; CG victims are FIFO-deferred and retried like ACG victims so fixed-workload finality requires every logical transaction to complete; BasicTopologicalSort remains reference serialization evidence; PBFT is unchanged"}),
_manifest("scheduler", "cg_scheduler", "CG / Nezha Scheduler", "Constructs Nezha NewBuildConflictGraph with official WW parallel-arc multiplicity and RW duplicate suppression; uses exact Tarjan/JohnsonCE/BreakCycles within budget and deterministic Johnson-prefix BreakCycles beyond it; cycle victims are consensus-bound Deferred retries; BasicTopologicalSort remains reference order evidence.", capabilities=["consensus_bound_schedule", "official_conflict_multigraph", "cycle_detection", "nezha_johnson_cycle_abort", "bounded_johnson_prefix_fallback", "fifo_deferred_retry_lifecycle", "basic_topological_sort_reference", "projection_validator"], requirements=["execution:cg_execution", "block_executor:cg_block_executor"], supported_backends=["real_cluster"], truth_boundary="nezha_cg_official_multigraph_bounded_johnson_retry_mbe_worker_v4"),
_manifest("block_executor", "cg_block_executor", "CG / Nezha MBE Worker Block Executor", "Executes only accepted dependency-ready frontiers from the consensus-bound Nezha-CG plan using the requested MBE worker count. Cycle victims remain algorithmic abort evidence but are non-terminal FIFO Deferred retries; no failed no-op receipt is emitted.", config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}), capabilities=["parallel_execution_adaptation", "dependency_ready_frontiers", "deterministic_materialization", "deterministic_cycle_abort_evidence", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_cg_official_multigraph_bounded_johnson_retry_mbe_worker_v4"),
    _manifest("execution", "acg_execution", "ACG / Nezha Execution", "Official-reference Nezha address-conflict-graph and hierarchical-sorting classifier; MBE retries HS-aborted logical transactions only at the experiment lifecycle layer.", capabilities=["paper_baseline_acg", "address_conflict_queues", "hierarchical_sorting", "deterministic_hs_abort_evidence", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_acg_hs_official_reference_mbe_retry_v2", source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Nezha: Exploiting Concurrency for Transaction Processing in DAG-based Blockchains", "doi": "10.1109/ICDCS54860.2022.00034", "official_repository": "CGCL-codes/Nezha", "implementation_note": "CreateGraph -> QueuesSort -> DeSS is unchanged; HS abort -> FIFO Deferred retry is an MBE experiment-lifecycle adaptation, not a claim about the Nezha reference benchmark"}),
    _manifest("scheduler", "acg_scheduler", "ACG / Nezha Scheduler", "Runs one first-pass Nezha CreateGraph -> QueuesSort -> DeSS plan, consensus-binds the accepted/deferred projection, and returns HS victims through the existing FIFO Deferred path.", capabilities=["consensus_bound_schedule", "address_conflict_queues", "hierarchical_sorting", "deterministic_hs_abort_evidence", "fifo_deferred_retry_lifecycle"], requirements=["execution:acg_execution", "block_executor:acg_block_executor"], supported_backends=["real_cluster"], truth_boundary="nezha_acg_hs_official_reference_mbe_retry_v2"),
    _manifest("block_executor", "acg_block_executor", "ACG / Nezha Block Executor", "Executes only the consensus-bound accepted Nezha HS waves; HS victims stay non-terminal and retry in a later block while abort evidence remains exported.", config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}), capabilities=["parallel_execution", "deterministic_materialization", "deterministic_hs_abort_evidence", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_acg_hs_official_reference_mbe_retry_v2"),
    _manifest("execution", "bsx_execution", "BSX Execution", "Batch-Schedule-Execute conflict-graph coloring classifier.", capabilities=["paper_baseline_bsx", "undirected_conflict_graph"], supported_backends=["real_cluster"], truth_boundary="bsx_homogeneous_conflict_graph_coloring_dsatur_v1", source={"source_type": "paper_reimplementation", "source_name": "Batch-Schedule-Execute: On Optimizing Concurrent Deterministic Scheduling for Blockchains", "doi": "10.1109/SRDS64841.2024.00025", "arxiv": "2402.05535"}),
    _manifest("scheduler", "bsx_scheduler", "BSX Scheduler", "Builds an undirected conflict graph and applies deterministic DSATUR coloring for the homogeneous-transaction scheduling case.", capabilities=["consensus_bound_schedule", "undirected_conflict_graph", "deterministic_dsatur_coloring"], requirements=["execution:bsx_execution", "block_executor:bsx_block_executor"], supported_backends=["real_cluster"], truth_boundary="bsx_homogeneous_conflict_graph_coloring_dsatur_v1"),
    _manifest("block_executor", "bsx_block_executor", "BSX Block Executor", "Executes one independent color class in parallel before advancing to the next color.", config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}), capabilities=["parallel_execution", "deterministic_materialization"], supported_backends=["real_cluster"], truth_boundary="bsx_homogeneous_conflict_graph_coloring_dsatur_v1"),
    _manifest("state_access", "direct_state_access", "Direct State Access", "Direct deterministic state database access."),
    _manifest("state_storage", "persistent_local_state_store", "Persistent Local State Store", "Per-node persisted state, block, receipt, and transaction index files.", capabilities=["persistent_state", "state_root"]),
    _manifest("cross_shard", "relay_certificate_protocol", "Relay Certificate Cross-shard", "SourceLock, relay certificate, target commit, source finalization, and timeout/refund evidence.", capabilities=["cross_shard", "relay_certificate"]),
    _manifest("commit", "normal_commit", "Normal Commit", "Durable deterministic commit."),
    _manifest("commit", "commutative_hot_update_aggregation", "Commutative Hot-update Aggregation", "Commit profile that records aggregation decisions for hot updates.", aliases=["aggregation"]),
    _manifest("fault_injection", "faults_disabled", "Faults Disabled", "No network fault policy."),
    _manifest("fault_injection", "network_delay_drop", "Network Delay and Drop", "Deterministic real TCP delay/drop policy.", config={"delay_ms": 5, "drop_every": 0}, schema=_schema({"delay_ms": {"type": "integer", "minimum": 0, "maximum": 1000, "default": 5}, "drop_every": {"type": "integer", "minimum": 0, "maximum": 10000, "default": 0}})),
    _manifest("metrics", "runtime_core_metrics", "Runtime Core Metrics", "Runtime counters and state-root summaries.", metrics=[{"key": "committed_block_count", "type": "integer", "unit": "block", "aggregation": "sum", "visualization": "summary", "description": "Committed blocks."}, {"key": "state_root_consistent", "type": "ratio", "unit": "boolean", "aggregation": "all", "visualization": "summary", "description": "Validator roots agree within every shard."}]),
    _manifest("observability", "node_network_consensus_observer", "Node, Network, and Consensus Observer", "Node logs, TCP logs, consensus logs, and artifact catalog."),
    # MBE_CALVIN_DUAL_REPRO_V2_20260923: paper-locked Calvin baseline plus explicit stateless adaptation.
    _manifest("transaction_admission", "calvin_declared_access_admission", "Calvin Declared-access Admission", "Requires a signed complete AccessList before deterministic scheduling.", requirements=["static_read_write_set"], capabilities=["calvin_static_access"], source={"type": "paper_and_official_source_reimplementation", "paper": "Calvin: Fast Distributed Transactions for Partitioned Database Systems (SIGMOD 2012)", "repository": "https://github.com/yaledb/calvin", "repository_commit": "c1fb1a51584bb150a1c1e493469bd2d7ac0ff40a", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("routing", "calvin_global_routing", "Calvin Global Ordering Routing", "One MBE PBFT ordering domain with partitioned Calvin state/execution homes.", capabilities=["calvin_global_ordering", "stateful_partitioned_execution"], source={"type": "paper_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("routing", "stateless_calvin_global_routing", "Stateless Calvin Global Ordering Routing", "Global Calvin order for the stateless compatibility profile; MetaTrack control-plane capabilities are intentionally absent.", capabilities=["calvin_global_ordering", "stateless_calvin_adaptation"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("execution", "calvin_execution", "Calvin Deterministic Execution", "Executes transactions in the PBFT-bound global serial order after deterministic locks become ready.", capabilities=["deterministic_serial_equivalence", "no_conflict_abort"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("scheduler", "calvin_deterministic_scheduler", "Calvin Deterministic Lock Scheduler", "Per-key FIFO S/X lock queues with transaction wait counters and ready-queue wakeups.", capabilities=["fifo_shared_exclusive_locking", "global_order_determinism"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("scheduler", "stateless_calvin_deterministic_scheduler", "Stateless Calvin Consensus-Version Scheduler", "Calvin FIFO deterministic scheduling plus a PBFT-bound exact-version plan derived from final block order; used only by Stateless Calvin.", capabilities=["fifo_shared_exclusive_locking", "global_order_determinism", "consensus_bound_version_plan"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("block_executor", "calvin_block_executor", "Calvin Block Executor", "Stateful partition-resident Calvin execution with READ_RESULT forwarding and local-write ownership.", config={"worker_count": 4, "read_result_timeout_ms": 0, "outcome_timeout_ms": 0}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "read_result_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}, "outcome_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}}), capabilities=["calvin_read_result", "calvin_outcome_harmonization", "partition_resident_state", "no_2pc"], metrics=[{"key": "calvin_lock_wait_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "Deterministic lock waits."}, {"key": "calvin_remote_read_count", "type": "integer", "unit": "read", "aggregation": "sum", "visualization": "summary", "description": "Remote READ_RESULT values consumed."}], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("block_executor", "stateless_calvin_block_executor", "Stateless Calvin Block Executor", "Compatibility adaptation that physically fetches signed-AccessList values from deterministic state homes after Calvin lock readiness and writes produced values back to those persistent homes.", config={"worker_count": 4, "read_result_timeout_ms": 0, "outcome_timeout_ms": 0}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "read_result_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}, "outcome_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}}), capabilities=["calvin_outcome_harmonization", "stateless_calvin_adaptation", "physical_remote_state_fetch", "physical_remote_state_writeback", "exact_state_version_fetch", "consensus_bound_version_plan", "block_start_committed_value", "no_2pc", "no_metatrack_state_ready"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("state_access", "calvin_partition_state_access", "Calvin Partition State Access", "Partition-resident state reads plus Calvin READ_RESULT forwarding.", capabilities=["calvin_partition_resident_state"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("state_access", "stateless_calvin_state_access", "Stateless Calvin State Access", "Physical deterministic state-home access used only by the Stateless Calvin adaptation; predecessor/producer versions are bound to the PBFT-bound final candidate Calvin block order.", capabilities=["declared_state_projection", "signed_access_projection", "remote_state_fetch", "remote_state_writeback", "exact_state_version_fetch", "consensus_bound_version_plan"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("state_storage", "calvin_partition_state_store", "Calvin Partition State Store", "Persists state by ExecutionShardID while the PBFT ShardID remains one global ordering domain.", capabilities=["execution_shard_storage_identity", "persistent_partition_state"], source={"type": "mbe_platform_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("cross_shard", "calvin_no_2pc_coordinator", "Calvin Participant Protocol", "Disables MBE Relay/Finalize and traditional 2PC; distributed reads use Calvin READ_RESULT.", capabilities=["calvin_read_result", "no_2pc", "no_legacy_relay"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    # MBE_PORYGON_PAPER_REPRO_20260921_V8_REFACTOR: Porygon v8 single-ordering-domain / logical-ESC reimplementation.
    _manifest(
        "routing", "porygon_stateless_routing", "Porygon Stateless Ordering-domain Routing",
        "Routes every Porygon transaction into one physical MBE/PBFT ordering domain. Logical execution sharding is owned by the Porygon consensus-bound ESC plan, not MBE BatchRouting.",
        capabilities=["single_physical_ordering_domain", "signed_access_plan_binding", "no_meta_remote_state_control_plane"],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_single_physical_ordering_domain_logical_esc_v2",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "block_producer", "porygon_transaction_block_producer", "Porygon Transaction Block Producer",
        "Builds a Transaction Block and binds transaction/access roots plus full-body witness evidence before PBFT. The configured witness_threshold is retained as reproduction metadata; the MBE adaptation uses full validator recomputation before PBFT voting rather than a separate Witness Committee quorum.",
        config={"block_size": 100, "interval_ms": 75, "witness_threshold": 1},
        schema=_schema({"block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "transaction_block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75}, "witness_threshold": {"type": "integer", "minimum": 1, "maximum": 1024, "default": 1}}),
        capabilities=["porygon_transaction_block", "transaction_root", "signed_access_root", "full_body_data_availability_commitment", "proposal_evidence"],
        requirements=["routing:porygon_stateless_routing", "scheduler:porygon_pipeline_scheduler", "block_executor:porygon_block_executor"],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_transaction_block_full_body_validator_recompute_v3;witness_threshold_is_metadata_not_independent_quorum",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "execution", "porygon_execution", "Porygon Execution Classifier",
        "Execution classification for globally ordered transactions assigned to logical execution sub-committees by sender identity.",
        capabilities=["porygon_global_order", "execution_subcommittee", "sender_identity_partition"], supported_backends=["real_cluster"],
        truth_boundary="porygon_global_order_then_single_esc_execution_v2",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "scheduler", "porygon_pipeline_scheduler", "Porygon 3D Parallelism Planner",
        "Binds logical Witness/Ordering/Execution/Commit slots, Cross-Batch Witness evidence, sender-based ESC assignments, signed-access state locks, conflict-safe waves, and Single-Shard Execution/Multi-Shard Update plans before consensus.",
        config={"execution_shard_count": 4, "execution_committee_count": 3, "pipeline_enabled": True, "cross_batch_witness": True},
        schema=_schema({"execution_shard_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "execution_committee_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 3}, "pipeline_enabled": {"type": "boolean", "default": True}, "cross_batch_witness": {"type": "boolean", "default": True}}),
        capabilities=["porygon_witness_order_execute_commit", "cross_batch_witness", "execution_subcommittee_sharding", "signed_access_state_locking", "consensus_bound_execution_plan", "single_esc_cross_shard_execution"],
        requirements=["routing:porygon_stateless_routing", "block_producer:porygon_transaction_block_producer", "execution:porygon_execution", "block_executor:porygon_block_executor", "state_access:porygon_remote_state_access", "cross_shard:porygon_cross_shard_coordinator", "consensus:pbft_style_consensus"],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_3d_parallelism_plan_v2;pipeline_slots_are_protocol_evidence_not_wall_clock_overlap",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "block_executor", "porygon_block_executor", "Porygon Logical-ESC Block Executor",
        "Executes conflict-safe logical ESC waves from the consensus-bound plan. Each cross-ESC transaction executes exactly once; signed AccessList visibility is enforced and writes are atomically materialized in the common ordering domain.",
        config={"worker_count": 4, "execution_shard_count": 4, "execution_committee_count": 3, "pipeline_enabled": True, "cross_batch_witness": True},
        schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4}, "execution_shard_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "execution_committee_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 3}, "pipeline_enabled": {"type": "boolean", "default": True}, "cross_batch_witness": {"type": "boolean", "default": True}}),
        capabilities=["porygon", "logical_execution_subcommittee", "parallel_waves", "single_execution_cross_shard", "signed_access_projection", "deterministic_multi_state_update", "execution_plan_digest", "no_meta_remote_state_control_plane"],
        requirements=["scheduler:porygon_pipeline_scheduler", "execution:porygon_execution", "routing:porygon_stateless_routing", "state_access:porygon_remote_state_access", "consensus:pbft_style_consensus"],
        metrics=[
            {"key": "porygon_witnessed_block_count", "type": "integer", "unit": "block", "aggregation": "sum", "visualization": "summary", "description": "Transaction blocks whose body/access roots were validated."},
            {"key": "porygon_execution_shard_count", "type": "integer", "unit": "shard", "aggregation": "max", "visualization": "summary", "description": "Configured logical execution sub-committee count."},
            {"key": "porygon_active_execution_shard_count", "type": "integer", "unit": "shard", "aggregation": "max", "visualization": "summary", "description": "Logical ESCs that executed at least one transaction."},
            {"key": "porygon_cross_shard_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions whose execution/state ownership spans multiple logical Porygon shards."},
            {"key": "porygon_single_shard_execution_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Logical cross-shard transactions executed exactly once by one ESC."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed concurrent Porygon transaction execution width."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_single_physical_ordering_domain_logical_esc_atomic_materialization_v2",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "state_access", "porygon_remote_state_access", "Porygon Signed-access State Projection",
        "Restricts each business execution to the state keys declared in its signed AccessList. The current MBE adaptation uses one physical PBFT/state domain and does not claim separate physical Storage Nodes.",
        capabilities=["signed_access_projection", "fail_closed_access_closure", "logical_storage_consensus_separation_evidence"],
        requirements=["routing:porygon_stateless_routing"], supported_backends=["real_cluster"],
        truth_boundary="porygon_signed_access_projection_over_single_mbe_state_domain_v2;separate_physical_storage_nodes_not_claimed",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "cross_shard", "porygon_cross_shard_coordinator", "Porygon Logical Cross-shard Coordinator",
        "Declares logical state-lock / Single-Shard Execution / Multi-Shard Update semantics. It intentionally never activates MBE's physical Relay/Finalize protocol.",
        config={"execution_shard_count": 4}, schema=_schema({"execution_shard_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}),
        capabilities=["logical_porygon_state_lock", "single_esc_execution", "atomic_multi_state_update", "physical_relay_disabled"],
        requirements=["routing:porygon_stateless_routing", "block_executor:porygon_block_executor"], supported_backends=["real_cluster"],
        truth_boundary="porygon_logical_cross_shard_coordination_inside_single_ordering_domain_v2",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
]


class PluginManifestStore:
    def __init__(self, manifests: Iterable[V5PluginManifest] = _MANIFESTS):
        self._items = list(manifests)
        seen: set[tuple[str, str, str]] = set()
        for item in self._items:
            if item.category not in CATEGORIES:
                raise ValueError(f"unknown plugin category: {item.category}")
            key = (item.plugin_id, item.category, item.version)
            if key in seen:
                raise ValueError(f"duplicate plugin manifest: {item.plugin_id}")
            seen.add(key)

    def list(self) -> list[V5PluginManifest]:
        return list(self._items)

    def get(self, plugin_id: str) -> V5PluginManifest:
        for item in self._items:
            if item.plugin_id == plugin_id or plugin_id in item.legacy_aliases:
                return item
        raise ValueError(f"unknown plugin: {plugin_id}")


STORE = PluginManifestStore()
