from __future__ import annotations

from collections.abc import Iterable

from backend.app.models.v5_plugin import V5PluginManifest


CATEGORIES = (
    "workload", "transaction_admission", "txpool", "sharding", "routing",
    "block_producer", "consensus", "network", "execution", "scheduler",
    "block_executor", "state_access", "state_storage", "cross_shard", "commit", "fault_injection",
    "metrics", "observability",
)


def _schema(properties: dict) -> dict:
    return {"type": "object", "properties": properties}


_ZH = {
    "deterministic_signed_synthetic": ("确定性签名合成负载", "生成带签名的确定性片内、跨片及超时退款交易。"),
    "signature_nonce_admission": ("签名与随机数准入", "校验 Ed25519 签名、发送方公钥绑定和随机数。"),
    "metatrack_strict_admission_v1": ("MetaTrack 严格访问声明准入", "在签名校验基础上要求结构化访问声明完整、状态键唯一且访问模式明确。"),
    "fifo_per_node_mempool": ("每节点 FIFO 交易池", "每个节点维护独立的 FIFO 交易池。"),
    "deterministic_state_key_sharding": ("确定性状态键分片", "将账户和状态键映射到配置的分片。"),
    "hash_routing_baseline": ("有状态哈希路由参考", "按源分片执行并使用本地状态的历史参考路由。"),
    "stateless_hash_routing": ("无状态哈希路由基线", "使用确定性状态归属、远程状态获取与写回的公平无状态哈希路由。"),
    "porygon_stateless_routing": ("Porygon 单排序域路由", "所有交易进入同一物理 PBFT 排序域，逻辑执行分片由 Porygon ESC 计划完成。"),
    "porygon_transaction_block_producer": ("Porygon 交易块装配器", "构造交易块并形成真实 EC Witness Certificate 后进入排序。"),
    "porygon_execution": ("Porygon 执行分类", "全局排序后按发起账户/对象状态归属确定动态执行子委员会。"),
    "porygon_pipeline_scheduler": ("Porygon 三维并行规划器", "构造真实 Cross-Batch Witness、跨高度 W/O/E/M 生命周期、动态 ESC、跨轮 Pending CTx 冲突控制和跨片计划。"),
    "porygon_block_executor": ("Porygon 分片执行器", "按动态 ESC 批执行，形成批级结果证书并执行 Multi-Shard Update。"),
    "porygon_remote_state_access": ("Porygon 可验证状态投影", "按签名 AccessList 获取 StateOwner 状态并验证 Merkle 证明；不复用 MetaTrack CAS。"),
    "calvin_global_routing": ("Calvin 全局排序路由", "Calvin 有状态基线：所有交易进入统一 PBFT 排序域，状态仍按执行分区持有。"),
    "stateless_calvin_global_routing": ("Stateless Calvin 全局排序路由", "Calvin 无状态适配：统一 PBFT 排序域，不激活 MetaTrack 路由控制面。"),
    "calvin_declared_access_admission": ("Calvin 静态访问声明准入", "要求签名 AccessList 完整且仅包含确定读写模式。"),
    "calvin_execution": ("Calvin 确定性执行", "按照共识确定的全局事务顺序执行。"),
    "calvin_deterministic_scheduler": ("Calvin 确定性锁调度", "每键 FIFO 共享/排他锁、等待计数与 Ready Queue。"),
    "calvin_block_executor": ("Calvin 区块执行器", "有状态分区 Calvin：READ_RESULT + 本地写入 + 无冲突回滚。"),
    "stateless_calvin_block_executor": ("Stateless Calvin 区块执行器", "使用签名 AccessList 状态投影的 Calvin 兼容适配。"),
    "calvin_partition_state_access": ("Calvin 分区状态访问", "常驻分区状态与 READ_RESULT 读取转发。"),
    "stateless_calvin_state_access": ("Stateless Calvin 状态访问", "仅向执行器暴露声明状态投影。"),
    "calvin_partition_state_store": ("Calvin 分区状态存储", "按 ExecutionShardID 隔离的持久状态与证据存储。"),
    "calvin_no_2pc_coordinator": ("Calvin 无 2PC 协调", "关闭 MBE Relay/Finalize；跨分区依赖由 Calvin READ_RESULT 与确定性锁处理。"),
    "porygon_cross_shard_coordinator": ("Porygon 跨片协调", "执行 Single-Shard Execution、跨轮 ESC handoff、Multi-Shard Update、ACK 与显式 rollback certificate；不触发 MBE Relay/Finalize。"),
    "metatrack_coaccess_routing": ("MetaTrack 共访存路由", "按批次访问频率与状态共现构造有容量约束的执行侧状态放置，并以 MajorityPlace 决定交易执行分片。"),
    "metatrack_home_exact_access": ("MetaTrack Home exact 状态访问", "exact-version 统一经持久 Home 发布与获取。"),
    "metatrack_local_exact_access": ("MetaTrack 本地 exact 状态访问", "优先使用执行域本地 exact-version，缺失时回退 Home。"),
    "metatrack_route_batch_producer": ("MetaTrack 固定批次出块器", "一个完整 RouteBatch 对应一个签名共识窗口与 PBFT 单元。"),
    "metatrack_dependency_window_producer": ("MetaTrack 依赖窗口出块器", "恢复原始 V661 关键路径保持规则：只有合并不延长已有执行关键路径时才聚合连续 RouteBatch；PBFT 不变。"),
    "metatrack_single_conservative_execution": ("MetaTrack 单保守轨", "复用同一依赖 DAG 与有效前沿证据，但所有交易统一进入保守轨。"),
    "metatrack_single_execution": ("MetaTrack 单轨统一就绪执行", "保留执行依赖 DAG 与 StateReady，但不进行 Fast/Conservative 轨道判定；所有已就绪交易进入统一 FIFO Ready 队列。"),
    "metatrack_hash_routing": ("MetaTrack 哈希分流", "以确定性哈希替代 MetaTrack 智能执行分片选择，但保留 MetaTrack 签名路由、版本依赖与 StateReady 元数据。"),
    "time_or_count_block_producer": ("时间或数量出块器", "Leader 按时间间隔或交易池数量持续提议区块。"),
    "metatrack_adaptive_window_producer": ("MetaTrack 自适应聚合共识实验", "恢复 v6.5.6.8 原始 N/L 自适应窗口；仅在加入下一完整 RouteBatch 后 N/L 严格提高时聚合，无经验阈值。"),
    "aria_block_producer": ("Aria 批次区块装配器", "按同一状态快照执行一个 Aria 批次，将可提交交易组装入当前区块，并将冲突交易按原顺序留到后续区块。"),
    "groundhog_block_producer": ("Groundhog 区块装配器", "基于同一快照解释候选交易并通过类型化状态预留筛选可共同成立的区块交易。"),
    "pbft_style_consensus": ("PBFT 风格共识", "基于本地 TCP 的 PrePrepare、Prepare 和 Commit 法定人数消息流程。"),
    "localhost_tcp_typed_network": ("本地 TCP 类型化网络", "在独立 localhost TCP 监听器上传输类型化消息。"),
    "serial_execution_baseline": ("串行执行基线", "确定性的串行执行基线。"),
    "batch_si_execution": ("Batch-SI 执行分类器", "仅为 Batch-SI 提供独立的执行轨分类，不调用其他方案算法代码。"),
    "dual_track_execution": ("双轨执行", "记录快速轨与保守轨执行证据的确定性执行插件。"),
    "fifo_serial_scheduler": ("FIFO 串行调度器", "对已准入交易进行 FIFO 调度。"),
    "fast_first_scheduler": ("快速优先调度器", "用于双轨执行的快速优先调度器。"),
    "dependency_influence_scheduler": ("依赖关键交易优先调度器", "仅在依赖与 StateReady 已满足的交易之间，按后向依赖深度 H、后继数量 D、规范顺序依次优先。"),
    "ready_round_control_scheduler": ("就绪轮次对照调度器", "与依赖关键交易优先使用相同的就绪轮次与统一 Worker 模型，但轮次内保持快速轨优先并按规范顺序仲裁。"),
    "batch_si_scheduler": ("Batch-SI 批次规划器", "在共识前独立执行 AWRT、WRBP 与 OFAS，并将确定性批次计划绑定到区块。"),
    "batch_si_block_executor": ("Batch-SI 批快照执行器", "按批次顺序、批内统一快照并行执行 Batch-SI 计划，不调用其他方案算法代码。"),
    "fabricpp_cg_execution": ("Fabric++ CG 执行分类", "Sharma 等 SIGMOD 2019 Fabric++ 传统冲突图执行分类。"),
    "fabricpp_cg_scheduler": ("Fabric++ CG 事务重排序", "按 WS(Ti)∩RS(Tj) 构造冲突图，Tarjan+Johnson 精确枚举周期并按最大周期参与度确定性移除事务，生成可串行化调度。"),
    "fabricpp_cg_block_executor": ("Fabric++ CG 区块执行器", "执行 Fabric++ 消环后的可串行化调度，并将 Algorithm 1 移除事务记录为确定性终态失败空操作。"),
    "cg_execution": ("CG / Nezha 执行分类", "Nezha 传统 CG：官方冲突多重图；可枚举区域使用完整 JohnsonCE，超预算区域使用确定性 Johnson 前缀消环；victim 延后重试。"),
    "cg_scheduler": ("CG / Nezha 冲突图调度", "按官方 NewBuildConflictGraph 保留 WW 重复弧；Tarjan + JohnsonCE/BreakCycles，超预算时以确定性 Johnson 前缀继续相同 victim 规则，并将 victim 延后重试。"),
    "cg_block_executor": ("CG / Nezha MBE Worker 执行器", "只执行当前 accepted CG frontiers；cycle victim 不生成终态失败回执，而是返回 FIFO mempool 后续重试。"),
    "acg_execution": ("ACG / Nezha 执行分类", "Nezha 地址冲突图与层次排序；HS 中止由 MBE 生命周期延后重试。"),
    "acg_scheduler": ("ACG / Nezha 地址冲突图调度", "CreateGraph → QueuesSort → DeSS 保持不变，HS victim 通过 Deferred 留待后续区块。"),
    "acg_block_executor": ("ACG / Nezha 并行执行器", "只执行当前区块 accepted HS waves；deferred victim 不在本块生成终态失败回执。"),
    "bsx_execution": ("BSX 执行分类", "论文对照组：无向冲突图着色调度。"),
    "bsx_scheduler": ("BSX 图着色调度", "构造无向冲突图并使用确定性 DSATUR 启发式着色。"),
    "bsx_block_executor": ("BSX 并行执行器", "同色无冲突事务并行、颜色批次顺序推进。"),
    "aria_block_executor": ("Aria 批量乐观执行器", "验证固定 Aria 批次在同一快照、读写预留与 Rule 2 下可以单纪元提交。"),
    "groundhog_block_executor": ("Groundhog 无序区块执行器", "对固定区块执行同快照类型化修改验证、约束合并和确定性状态物化。"),
    "direct_state_access": ("直接状态访问", "直接访问确定性状态数据库。"),
    "persistent_local_state_store": ("本地持久化状态存储", "每个节点持久化状态、区块、回执和交易索引。"),
    "relay_certificate_protocol": ("中继证书跨片协议", "提供 SourceLock、中继证书、TargetCommit、SourceFinalize 与超时退款证据。"),
    "normal_commit": ("普通提交", "确定性的持久化提交。"),
    "commutative_hot_update_aggregation": ("可交换热点更新聚合", "记录热点更新聚合决策的提交配置。"),
    "faults_disabled": ("禁用故障注入", "不施加网络故障策略。"),
    "network_delay_drop": ("网络延迟与丢包", "确定性的真实 TCP 延迟和丢包策略。"),
    "runtime_core_metrics": ("运行时核心指标", "运行时计数器和状态根汇总。"),
    "node_network_consensus_observer": ("节点网络共识观测器", "生成节点、TCP、共识日志和产物目录。"),
}


def _manifest(category: str, plugin_id: str, display_name: str, description: str, *,
              config: dict | None = None, schema: dict | None = None, capabilities: list[str] | None = None,
              requirements: list[str] | None = None, metrics: list[dict] | None = None,
              aliases: list[str] | None = None, supported_backends: list[str] | None = None,
              truth_boundary: str = "v5_real_cluster_candidate", source: dict | None = None) -> V5PluginManifest:
    display_name_zh, description_zh = _ZH.get(plugin_id, (display_name, description))
    return V5PluginManifest(
        plugin_id=plugin_id, category=category, display_name=display_name, description=description,
        display_name_zh=display_name_zh, description_zh=description_zh,
        supported_backends=supported_backends or ["preview", "simulation", "real_cluster"],
        config_schema=schema or _schema({}), default_config=config or {}, capabilities=capabilities or [],
        requirements=requirements or [], metrics=metrics or [], runtime_factory=f"builtin:{plugin_id}",
        runtime_adapter="go_factory_registry", truth_boundary=truth_boundary, source=source or {}, legacy_aliases=aliases or [],
    )


_MANIFESTS = [
    _manifest("workload", "deterministic_signed_synthetic", "Deterministic Signed Synthetic", "Deterministic signed workload with intra-shard, relay, and timeout cases.", config={"cross_shard_ratio": 0.25, "timeout_every": 17}, schema=_schema({"cross_shard_ratio": {"type": "number", "minimum": 0, "maximum": 1, "default": 0.25}, "timeout_every": {"type": "integer", "minimum": 0, "maximum": 1000, "default": 17}}), metrics=[{"key": "submitted_tx_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions submitted over TCP."}]),
    _manifest("workload", "canonical_trace_replay", "Canonical Trace Replay", "Streams deterministic materialized dataset workload records through a manifest-owned universal access-list contract.", config={}, schema=_schema({"dataset_id": {"type": "string"}, "variant_mode": {"type": "string"}, "selection_mode": {"type": "string", "enum": ["contiguous_window", "validated_prefix"]}, "skew_axis": {"type": ["string", "null"]}, "target_alpha": {"type": ["number", "null"]}, "variant_parameters": {"type": "object"}}), capabilities=["dataset_replay", "gzip_streaming", "manifest_variants", "direct_access_list_v3", "no_fallback"], metrics=[{"key": "workload_replay_read_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Canonical workload records read by the client."}]),
    _manifest("transaction_admission", "signature_nonce_admission", "Signature and Nonce Admission", "Ed25519 signature, sender/public-key binding, and nonce admission.", capabilities=["signed_tx", "nonce_validation"]),
    _manifest("transaction_admission", "metatrack_strict_admission_v1", "MetaTrack Strict Access Admission", "MetaTrack-only signature admission with mandatory structured access declarations.", capabilities=["signed_tx", "nonce_validation", "declared_access_required"]),
    _manifest("txpool", "fifo_per_node_mempool", "FIFO Per-node Mempool", "Independent FIFO mempool on every node.", config={"capacity": 10000}, schema=_schema({"capacity": {"type": "integer", "minimum": 100, "maximum": 100000, "default": 10000}})),
    _manifest("sharding", "deterministic_state_key_sharding", "Deterministic State-key Sharding", "Maps account/state keys to a configured shard.", capabilities=["multi_shard"]),
    _manifest("routing", "hash_routing_baseline", "Stateful Hash Routing Reference", "Historical source-shard execution reference with local state access.", aliases=["hash"], capabilities=["stateful_local_execution"], truth_boundary="stateful_reference_not_directly_comparable_to_stateless_methods", metrics=[{"key": "routing_decision_count", "type": "integer", "unit": "decision", "aggregation": "sum", "visualization": "summary", "description": "Routing decisions made by the client."}]),
    _manifest("routing", "stateless_hash_routing", "Stateless Hash Routing Baseline", "Fair stateless hash baseline with deterministic state homes, exact per-key logical-version fetch for non-commutative business state, and home-shard writeback.", aliases=["stateless_hash"], capabilities=["batch_routing", "stateless_direct_execution", "remote_state_fetch", "remote_state_writeback", "exact_state_version_fetch", "per_key_version_writeback_frontier"], truth_boundary="stateless_hash_remote_home_exact_version_v2", metrics=[{"key": "routing_decision_count", "type": "integer", "unit": "decision", "aggregation": "sum", "visualization": "summary", "description": "Stateless hash routing decisions made by the client."}]),
    _manifest(
        "routing", "metatrack_coaccess_routing", "MetaTrack Co-access Routing",
        "Execution sharding from state access/co-access evidence; the latest profile can additionally preserve exact-version execution continuity across signed RouteBatch boundaries with deterministic workload-derived capacity.",
        config={"routing_epoch": 0},
        schema=_schema({
            "routing_epoch": {"type": "integer", "minimum": 0, "maximum": 1000000000, "default": 0},
            "control_policy": {"type": "string", "enum": ["legacy_v2", "logical_domain_frontier_v1", "declared_access_frontier_v2"], "default": "legacy_v2"},
            "logical_domain_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4},
            "state_storage_unit_count": {"type": "integer", "minimum": 0, "maximum": 65536, "default": 0},
            "micro_batch_size": {"type": "integer", "minimum": 0, "maximum": 5000, "default": 0},
            "incremental_exact_continuity_routing_v65": {"type": "boolean", "default": False},
            "ablation_ignore_exact_ready_routing_v660": {"type": "boolean", "default": False},
            "ablation_ignore_coaccess_routing_v661": {"type": "boolean", "default": False},
            "ablation_hash_routing_v662": {"type": "boolean", "default": False},
            "stream_partition_invariant_v658": {"type": "boolean", "default": False},
            "placement_mu": {"type": "number", "minimum": 0.01, "maximum": 64.0, "default": 1.0},
            "placement_min_budget": {"type": "integer", "minimum": 1, "maximum": 1000000, "default": 1},
        }),
        aliases=["co_access", "metatrack"],
        capabilities=["batch_routing", "batch_frequency_coaccess", "admissible_state_load_capacity", "per_seed_top_cooccur_budget", "majority_place_queue_tie", "routing_epoch_evidence", "predicted_remote_access_accounting", "stateless_direct_execution", "remote_state_fetch", "remote_state_writeback", "exact_state_version_fetch", "logical_state_storage_units", "state_unit_execution_role_separation", "configurable_placement_budget", "configurable_micro_batch_size", "incremental_exact_version_continuity", "route_batch_partition_invariant_routing", "stream_partition_invariant_routing"],
        truth_boundary="metatrack_batch_execution_sharding_admissible_capacity_v2",
        source={"source_type": "user_manuscript_algorithm_reimplementation", "source_name": "MetaTrack batch-level execution sharding"},
        metrics=[{"key": "metatrack_routed_tx_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions routed through the MetaTrack profile."}],
    ),
    _manifest(
        "routing", "metatrack_hash_routing", "MetaTrack Hash Routing",
        "Deterministic hash execution placement inside the same MetaTrack signed routing/version carrier.",
        config={"routing_epoch": 0},
        schema=_schema({
            "routing_epoch": {"type": "integer", "minimum": 0, "maximum": 1000000000, "default": 0},
            "control_policy": {"type": "string", "enum": ["legacy_v2", "logical_domain_frontier_v1", "declared_access_frontier_v2"], "default": "legacy_v2"},
            "state_storage_unit_count": {"type": "integer", "minimum": 0, "maximum": 65536, "default": 0},
            "micro_batch_size": {"type": "integer", "minimum": 0, "maximum": 5000, "default": 0},
            "incremental_exact_continuity_routing_v65": {"type": "boolean", "default": False},
        }),
        capabilities=["batch_routing", "stateless_direct_execution", "exact_state_version_fetch", "metatrack_signed_routing_carrier", "deterministic_hash_execution_placement"],
        truth_boundary="metatrack_hash_execution_placement_same_metadata_contract_v663",
    ),
    _manifest("block_producer", "time_or_count_block_producer", "Time or Count Block Producer", "Leader proposes blocks repeatedly by interval or mempool count. MetaTrack current mode preserves one complete signed route-batch projection per PBFT block; dependency-closed consensus mode greedily packs the largest safe prefix of complete signed projections without splitting a projection.", config={"block_size": 100, "interval_ms": 75}, schema=_schema({"block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75}, "dependency_closed_consensus": {"type": "boolean", "default": False}, "partition_invariant_consensus_v658": {"type": "boolean", "default": False}, "ablation_single_route_batch_consensus_v660": {"type": "boolean", "default": False}}), capabilities=["time_or_count_cut", "metatrack_complete_projection_preconsensus_aggregation", "metatrack_dependency_closed_projection_prefix", "metatrack_partition_invariant_frontier_v658"]),
    _manifest("block_producer", "metatrack_dependency_window_producer", "MetaTrack Dependency Window Producer", "MetaTrack signed consensus-window producer using the original threshold-free V661 critical-path-preserving admission rule.", config={"block_size": 100, "interval_ms": 75}, schema=_schema({"block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75}}), capabilities=["metatrack_signed_window", "critical_path_preserving_dependency_window_v661"]),
    _manifest("block_producer", "metatrack_route_batch_producer", "MetaTrack RouteBatch Producer", "MetaTrack fixed RouteBatch consensus-window producer: exactly one complete RouteBatch per PBFT unit.", config={"block_size": 100, "interval_ms": 75}, schema=_schema({"block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75}}), capabilities=["metatrack_signed_window", "single_route_batch_window"]),
    _manifest("block_producer", "metatrack_adaptive_window_producer", "MetaTrack Adaptive N/L Window Producer", "Experimental restoration of the original v6.5.6.8 complete-RouteBatch N/L adaptive consensus window. Joins only when N/L strictly improves and block_size remains satisfied; no empirical threshold.", config={"block_size": 100, "interval_ms": 75}, schema=_schema({"block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75}}), capabilities=["metatrack_complete_projection_preconsensus_aggregation", "metatrack_adaptive_n_over_l_window", "no_empirical_threshold"]),
    _manifest(
        "block_producer", "aria_block_producer", "Aria Block Producer",
        "Executes one deterministic Aria batch over the block-start snapshot, selects Rule-2-committable transactions for the current block, and releases deferred transactions back to FIFO mempool order for a later block.",
        config={
            "block_size": 100,
            "interval_ms": 75,
            "candidate_scan_multiplier": 1,
            "reordering": True,
            "read_only_optimization": True,
            "retry_nonce_gaps": True,
        },
        schema=_schema({
            "block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100},
            "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75},
            "candidate_scan_multiplier": {"type": "integer", "minimum": 1, "maximum": 32, "default": 1},
            "reordering": {"type": "boolean", "default": True},
            "read_only_optimization": {"type": "boolean", "default": True},
            "retry_nonce_gaps": {"type": "boolean", "default": True},
        }),
        capabilities=["aria_single_batch_assembly", "same_snapshot_execution", "rule2_conflict_selection", "fifo_deferred_transactions", "proposal_selection_evidence"],
        requirements=["block_executor:aria_block_executor", "routing:hash_routing_baseline", "execution:serial_execution_baseline", "scheduler:fifo_serial_scheduler", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="aria_rule2_one_consensus_block_per_batch_fallback_disabled",
        source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Aria: A Fast and Practical Deterministic OLTP Database", "doi": "10.14778/3407790.3407808", "source_repository": "https://github.com/luyi0619/aria", "source_commit": "d0508c393ec084582c12e6f3abadab63501eaedd", "reproduction_dossier": "docs/reproductions/aria/source_lock.md"},
    ),
    _manifest(
        "block_producer", "groundhog_block_producer", "Groundhog Block Producer",
        "Builds a Groundhog candidate by interpreting a wider FIFO candidate window against one block-start snapshot, reserving typed modifications, deferring only aggregate constraint conflicts, and preserving terminal application failures for final receipts.",
        # MBE_V37_PLUGIN_CONFIG_TRUTH: scan multiplier is retained only as an accepted legacy field.
        config={"block_size": 100, "interval_ms": 75, "ordered_set_limit": 64},
        schema=_schema({
            "block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100},
            "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75},
            "candidate_scan_multiplier": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4, "deprecated": True, "description": "Legacy compatibility only; current Groundhog scans the complete ready pool and ignores this value."},
            "ordered_set_limit": {"type": "integer", "minimum": 1, "maximum": 65535, "default": 64},
        }),
        capabilities=["groundhog_block_assembly", "same_snapshot_candidate_interpretation", "typed_state_reservation", "transaction_atomic_rollback", "constraint_conflict_deferral"],
        requirements=["block_executor:groundhog_block_executor", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store"],
        supported_backends=["real_cluster"],
        truth_boundary="groundhog_deterministic_candidate_assembly_over_concurrent_typed_reservation_validation;official_cpp_mempool_worker_race_not_reproduced",
        source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Groundhog: Linearly-Scalable Smart Contracting via Commutative Transaction Semantics", "arxiv": "2404.03201", "source_repository": "https://github.com/scslab/smart-contract-scalability", "source_commit": "6b357bc206b73ece39fd61fe7dba655352200c0a", "reproduction_dossier": "docs/reproductions/groundhog/source_lock.md"},
    ),
    _manifest("consensus", "pbft_style_consensus", "PBFT-style Consensus", "Local TCP PBFT-style PrePrepare, Prepare, and Commit quorum runtime.", capabilities=["pbft_messages", "quorum_commit"]),
    _manifest("network", "localhost_tcp_typed_network", "Localhost TCP Typed Network", "Typed message transport on distinct localhost TCP listeners.", capabilities=["tcp", "typed_messages"]),
    _manifest("execution", "serial_execution_baseline", "Serial Execution", "Deterministic serial execution baseline."),
    _manifest(
        "execution", "batch_si_execution", "Batch-SI Execution Classifier",
        "Private Batch-SI execution-track classifier. It only identifies transactions for the Batch-SI planner and does not reuse another scheme's algorithm implementation.",
        capabilities=["batch_si_execution_track", "no_cross_scheme_algorithm_reuse"],
        supported_backends=["real_cluster"],
        truth_boundary="batch_si_private_execution_classification_contract",
        source={"source_type": "paper_reimplementation", "source_name": "Batch-SI: Semi-Parallel Concurrency Scheme for Permissioned Blockchains Exploiting Batch Snapshot Isolation", "reproduction_dossier": "docs/reproductions/batch_si/source_lock.md"},
    ),
    _manifest(
        "execution", "dual_track_execution", "Dual-track Execution",
        "Deterministic fast/conservative admission driven by access stability, static dependency-frontier position, dependency-topology safety, and execution-semantic stability. Access-list size is diagnostic only and does not choose the track.",
        schema=_schema({"ablation_force_all_conservative_v659": {"type": "boolean", "default": False}}),
        aliases=["dual_track"],
        capabilities=["dual_track", "access_stability_admission", "dependency_frontier_fast_root", "dependency_frontier_conservative_nonroot", "semantic_stability_admission", "state_ready_orthogonal_to_track", "nontrivial_scc_conservative_fallback", "metatrack_ablation_force_all_conservative_v659"],
        truth_boundary="metatrack_dual_track_dependency_frontier_v2",
    ),
    _manifest("execution", "metatrack_single_execution", "MetaTrack Single-track Unified-ready Execution", "Builds the same execution dependency DAG and StateReady wait keys without Fast/Conservative track classification; the execution plugin declares a unified FIFO Ready policy consumed by the shared MetaTrack block executor.", capabilities=["metatrack_dependency_dag", "unified_ready_queue_policy", "state_ready_orthogonal_to_track", "no_dual_track_classification"]),
    _manifest("execution", "metatrack_single_conservative_execution", "MetaTrack Single Conservative Execution", "Uses the same MetaTrack dependency DAG/frontier evidence but assigns every transaction to the conservative track.", capabilities=["metatrack_dependency_dag", "single_conservative_track", "state_ready_orthogonal_to_track"]),
    _manifest("scheduler", "fifo_serial_scheduler", "FIFO Serial Scheduler", "FIFO scheduler for admitted transactions."),
    _manifest("scheduler", "fast_first_scheduler", "Fast-first Scheduler", "MetaTrack ready scheduler: Fast-first when dual-track is selected and a single conservative ready queue when all decisions are conservative."),
    _manifest("scheduler", "dependency_influence_scheduler", "Dependency-influence Scheduler", "Among already-ready MetaTrack transactions, prioritizes larger tail depth H, then larger descendant count D, then canonical routing ordinal.", requirements=["execution:dual_track_execution"], capabilities=["metatrack_dependency_influence_priority"], source={"type": "mbe_mechanism_candidate", "evidence": "metatrack_dependency_structure_v33"}),
    _manifest("scheduler", "ready_round_control_scheduler", "Ready-round Control Scheduler", "Uses non-waiting Ready Rounds and the same unified worker-lane model as the dependency-influence candidate, but preserves fast-first then canonical ordering within the oldest round.", requirements=["execution:dual_track_execution"], capabilities=["metatrack_ready_round_arbitration", "bounded_cross_round_bypass"]),
    _manifest(
        "scheduler", "batch_si_scheduler", "Batch-SI Batch Planner",
        "Independently constructs AWRT, applies WRBP, performs OFAS, defers cyclic transactions before consensus, and commits a deterministic batch plan to the block.",
        config={"partition_mode": "wrbp", "ordering_mode": "ofas", "priority_mode": "paper"},
        schema=_schema({
            "partition_mode": {"type": "string", "enum": ["wrbp", "sequential"], "default": "wrbp"},
            "ordering_mode": {"type": "string", "enum": ["ofas", "dependency_graph"], "default": "ofas"},
            "priority_mode": {"type": "string", "enum": ["paper", "txid"], "default": "paper"},
        }),
        capabilities=["batch_si", "awrt", "wrbp", "ofas", "pre_consensus_execution_plan", "deterministic_deferral"],
        requirements=["block_executor:batch_si_block_executor", "execution:batch_si_execution", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="batch_si_ordering_reimplementation_over_declared_mbe_access_lists",
        source={"source_type": "paper_reimplementation", "source_name": "Batch-SI: Semi-Parallel Concurrency Scheme for Permissioned Blockchains Exploiting Batch Snapshot Isolation", "reproduction_dossier": "docs/reproductions/batch_si/source_lock.md"},
    ),
    _manifest(
        "block_executor", "serial_block_executor", "Serial Block Executor",
        "Executes block transactions in original order through the generic block executor contract.",
        config={"worker_count": 1},
        schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 1, "default": 1, "readOnly": True}, "versioned_wave_policy": {"type": "string", "enum": ["strict_single_tx_block_order_v1", "maximal_compatible_exact_version_v1"], "default": "maximal_compatible_exact_version_v1"}}),
        capabilities=["serial_order", "deterministic_state_delta", "legacy_equivalence_oracle", "execution_plan_digest"],
        metrics=[
            {"key": "block_executor_id", "type": "string", "unit": "", "aggregation": "last", "visualization": "summary", "description": "Selected block executor plugin."},
            {"key": "block_execution_ms", "type": "number", "unit": "ms", "aggregation": "sum", "visualization": "summary", "description": "Block execution wall-clock time."},
            {"key": "executed_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions executed by the block executor."},
            {"key": "execution_plan_digest", "type": "string", "unit": "", "aggregation": "last", "visualization": "summary", "description": "Deterministic execution plan digest."},
            {"key": "plan_digest_consistent", "type": "ratio", "unit": "boolean", "aggregation": "all", "visualization": "summary", "description": "Committed nodes agree on plan digest evidence."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="legacy_faithful_reference_baseline",
        source={"source_type": "internal_reference", "source_name": "MBE legacy realism serial execution engine", "source_commit": "84f28f43f2cfe93864fd4e4b68377fcfd31a5595", "reproduction_dossier": "docs/reproductions/serial/source_lock.md"},
    ),
    _manifest(
        "block_executor", "metatrack_block_executor", "MetaTrack Block Executor",
        "Executes MetaTrack fast/conservative ready queues with dependency and transaction-level remote StateReady suspend/resume callbacks over MBE transfer semantics.",
        config={"worker_count": 4, "batch_entry_state_prefetch": False, "batch_remote_writeback": False, "safe_state_fold": False, "version_liveness": False, "final_version_batch_writeback": False, "dependency_closed_consensus": False, "version_liveness_indexed": False, "single_final_seal": False},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 8, "default": 4},
            "control_policy": {"type": "string", "enum": ["logical_domain_frontier_v1", "declared_access_frontier_v2"]},
            "local_exact_version_handoff": {"type": "boolean", "default": False},
            "ablation_on_demand_state_fetch_v661": {"type": "boolean", "default": False},
            "ablation_single_ready_queue_v661": {"type": "boolean", "default": False},
            "ablation_force_home_exact_v660": {"type": "boolean", "default": False},
            "batch_entry_state_prefetch": {"type": "boolean", "default": False},
            "batch_remote_writeback": {"type": "boolean", "default": False},
            "safe_state_fold": {"type": "boolean", "default": False},
            "version_liveness": {"type": "boolean", "default": False},
            "final_version_batch_writeback": {"type": "boolean", "default": False},
            "dependency_closed_consensus": {"type": "boolean", "default": False},
            "version_liveness_indexed": {"type": "boolean", "default": False},
            "single_final_seal": {"type": "boolean", "default": False},
        }),
        capabilities=["metatrack_ready_queues", "dependency_release", "transaction_level_remote_state_ready", "state_wait_suspend_resume", "batch_local_exact_version_handoff", "batch_entry_state_prefetch", "batch_remote_writeback", "safe_state_fold", "version_dependency_liveness", "final_version_batch_writeback", "dependency_closed_consensus", "indexed_version_dependency_liveness", "single_final_seal", "deterministic_state_delta", "execution_plan_digest"],
        metrics=[
            {"key": "fast_track_execution_instance_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Fast-track execution instances completed by MetaTrack."},
            {"key": "blocked_queue_max_depth", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum planned/actual dependency queue depth."},
            {"key": "wakeup_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "Dependency releases that moved transactions into ready queues."},
            {"key": "state_wait_blocked_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "Transactions suspended because one or more required remote state keys were not StateReady."},
            {"key": "state_ready_wakeup_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "StateReady arrivals that woke a suspended transaction."},
            {"key": "remote_state_fetch_completed_count", "type": "integer", "unit": "fetch", "aggregation": "sum", "visualization": "summary", "description": "Remote state fetches completed by transaction-level StateReady scheduling."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="metatrack_native_transaction_level_state_ready_suspend_resume",
    ),
    _manifest(
        "block_executor", "aria_block_executor", "Aria Block Executor",
        "Validates a fixed one-epoch Aria batch over the block-start snapshot using minimum-TID read/write reservations, Rule 2 deterministic reordering, and no serial or Calvin fallback.",
        config={
            "worker_count": 4,
            "reordering": True,
            "read_only_optimization": True,
            "retry_nonce_gaps": True,
        },
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4},
            "reordering": {"type": "boolean", "default": True},
            "read_only_optimization": {"type": "boolean", "default": True},
            "retry_nonce_gaps": {"type": "boolean", "default": True},
        }),
        capabilities=[
            "aria", "deterministic_batch_occ", "same_snapshot_epoch",
            "read_write_reservation", "deterministic_reordering_rule2",
            "single_epoch_fixed_block_validation", "execution_plan_digest",
        ],
        requirements=["block_producer:aria_block_producer", "routing:hash_routing_baseline", "execution:serial_execution_baseline", "scheduler:fifo_serial_scheduler", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        metrics=[
            {"key": "aria_epoch_count", "type": "integer", "unit": "epoch", "aggregation": "sum", "visualization": "summary", "description": "Aria execution/commit epochs completed; fixed blocks must report exactly one."},
            {"key": "aria_conflict_abort_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Conflict attempts rejected during fixed-block validation; expected to be zero."},
            {"key": "aria_candidate_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions inspected by the proposer-side Aria batch selection."},
            {"key": "aria_selected_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Rule-2-committable transactions selected into the consensus block."},
            {"key": "aria_deferred_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions retained in FIFO mempool order for a later block."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed concurrent Aria execution width."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="aria_rule2_one_consensus_block_per_batch_fallback_disabled",
        source={
            "source_type": "paper_and_official_source_reimplementation",
            "source_name": "Aria: A Fast and Practical Deterministic OLTP Database",
            "doi": "10.14778/3407790.3407808",
            "source_repository": "https://github.com/luyi0619/aria",
            "source_commit": "d0508c393ec084582c12e6f3abadab63501eaedd",
            "reproduction_dossier": "docs/reproductions/aria/source_lock.md",
        },
    ),
    _manifest(
        "block_executor", "groundhog_block_executor", "Groundhog Block Executor",
        "Reimplements Groundhog unordered-block execution over MBE transaction semantics using one block-start snapshot, typed commutative modifications, reserve/rollback validation, deterministic materialization, and no serial fallback.",
        config={"worker_count": 4, "ordered_set_limit": 64},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4},
            "ordered_set_limit": {"type": "integer", "minimum": 1, "maximum": 65535, "default": 64},
        }),
        capabilities=["groundhog", "unordered_block", "block_start_snapshot", "typed_commutative_modifications", "nonnegative_int64_set_add", "bytes_set", "ordered_set", "concurrent_reserve_commit_rollback", "transactional_reservation_rewind", "deterministic_materialization", "no_serial_fallback", "execution_plan_digest"],
        requirements=["block_producer:groundhog_block_producer", "routing:hash_routing_baseline", "execution:serial_execution_baseline", "scheduler:fifo_serial_scheduler", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        metrics=[
            {"key": "groundhog_execution_attempt_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Groundhog transaction interpretations against the common block snapshot."},
            {"key": "groundhog_reservation_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Typed modifications successfully reserved."},
            {"key": "groundhog_constraint_conflict_count", "type": "integer", "unit": "conflict", "aggregation": "sum", "visualization": "summary", "description": "Typed-state constraints that rejected a transaction or fixed block."},
            {"key": "groundhog_reservation_rollback_count", "type": "integer", "unit": "rollback", "aggregation": "sum", "visualization": "summary", "description": "Transaction-level reservation rollbacks."},
            {"key": "groundhog_integer_merge_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Nonnegative integer set-add modifications merged."},
            {"key": "groundhog_bytes_merge_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Byte-string set modifications merged."},
            {"key": "groundhog_ordered_set_merge_count", "type": "integer", "unit": "modification", "aggregation": "sum", "visualization": "summary", "description": "Ordered-set insert, clear, and limit modifications merged."},
            {"key": "groundhog_modified_key_count", "type": "integer", "unit": "key", "aggregation": "sum", "visualization": "summary", "description": "Distinct state keys materialized by Groundhog."},
            {"key": "groundhog_reservation_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum concurrent Groundhog reserve/revert/commit width over disjoint object reservations."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed concurrent Groundhog interpretation width."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="groundhog_supported_typed_state_semantics_with_concurrent_transactional_reserve_revert_commit;official_cpp_storage_engine_not_embedded",
        source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Groundhog: Linearly-Scalable Smart Contracting via Commutative Transaction Semantics", "arxiv": "2404.03201", "source_repository": "https://github.com/scslab/smart-contract-scalability", "source_commit": "6b357bc206b73ece39fd61fe7dba655352200c0a", "reproduction_dossier": "docs/reproductions/groundhog/source_lock.md"},
    ),
    _manifest(
        "block_executor", "block_stm_block_executor", "Block-STM Block Executor",
        "Reimplements the Block-STM speculative block execution mechanism over MBE transfer semantics with MVMemory, validation, abort, and deterministic ordered materialization.",
        config={"worker_count": 4, "maximum_incarnations": 0},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 8, "default": 4},
            "maximum_incarnations": {"type": "integer", "minimum": 0, "maximum": 1000000, "default": 0, "description": "0 disables the artificial per-transaction incarnation cap for formal experiments."},
            "scheduler_mode": {"type": "string", "enum": ["legacy_scan_v1", "priority_heap_v1"], "default": "legacy_scan_v1"},
            "dependency_wait_mode": {"type": "string", "enum": ["abort_new_incarnation_v1", "suspend_same_incarnation_v1"], "default": "abort_new_incarnation_v1"},
            "versioned_wave_policy": {"type": "string", "enum": ["maximal_compatible_exact_version_v1", "maximal_compatible_exact_version_v2"], "default": "maximal_compatible_exact_version_v1"},
        }),
        capabilities=["block_stm", "mvmemory", "speculative_execution", "captured_reads", "validation", "abort_reexecution", "estimate_dependency", "serial_equivalence"],
        requirements=["state_access:direct_state_access", "state_storage:persistent_local_state_store"],
        metrics=[
            {"key": "worker_count", "type": "integer", "unit": "worker", "aggregation": "last", "visualization": "summary", "description": "Configured Block-STM workers."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed Block-STM parallel width."},
            {"key": "abort_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Validation abort count."},
            {"key": "reexecution_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions re-executed after abort."},
            {"key": "dependency_wait_count", "type": "integer", "unit": "wait", "aggregation": "sum", "visualization": "summary", "description": "ESTIMATE/dependency waits."},
            {"key": "validation_failure_count", "type": "integer", "unit": "failure", "aggregation": "sum", "visualization": "summary", "description": "Read validation failures."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="block_stm_core_reimplementation_over_mbe_transaction_semantics",
        source={"source_type": "paper_and_source_reimplementation", "source_name": "Block-STM: Scaling Blockchain Execution by Turning Ordering Curse to a Performance Blessing", "arxiv": "2203.06871v3", "source_repository": "https://github.com/aptos-labs/aptos-core", "source_commit": "20f9379515358add43f4042693462aaedd654826", "reproduction_dossier": "docs/reproductions/block_stm/source_lock.md"},
    ),
    _manifest(
        "block_executor", "batch_si_block_executor", "Batch-SI Block Executor",
        "Executes the committed Batch-SI plan with sequential batches, one immutable snapshot per batch, parallel transactions inside a batch, and deterministic state materialization using Batch-SI-owned transaction semantics.",
        config={"worker_count": 4, "partition_mode": "wrbp", "ordering_mode": "ofas", "priority_mode": "paper", "execution_mode": "snapshot_parallel"},
        schema=_schema({
            "worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4},
            "partition_mode": {"type": "string", "enum": ["wrbp", "sequential"], "default": "wrbp"},
            "ordering_mode": {"type": "string", "enum": ["ofas", "dependency_graph"], "default": "ofas"},
            "priority_mode": {"type": "string", "enum": ["paper", "txid"], "default": "paper"},
            "execution_mode": {"type": "string", "enum": ["snapshot_parallel", "snapshot_serial"], "default": "snapshot_parallel"},
        }),
        capabilities=["batch_si", "batch_snapshot_isolation", "sequential_batches", "intra_batch_parallelism", "deterministic_state_delta", "execution_plan_digest", "no_cross_scheme_algorithm_reuse"],
        requirements=["scheduler:batch_si_scheduler", "routing:hash_routing_baseline", "execution:batch_si_execution", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        metrics=[
            {"key": "configured_worker_count", "type": "integer", "unit": "worker", "aggregation": "last", "visualization": "summary", "description": "Configured Batch-SI intra-batch workers."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed intra-batch parallel width."},
            {"key": "batch_count", "type": "integer", "unit": "batch", "aggregation": "sum", "visualization": "summary", "description": "WRBP execution batches."},
            {"key": "maximum_batch_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Largest Batch-SI batch width."},
            {"key": "write_opportunity_reuse_count", "type": "integer", "unit": "opportunity", "aggregation": "sum", "visualization": "summary", "description": "WRBP write-opportunity batch assignments reused."},
            {"key": "dependency_edge_count", "type": "integer", "unit": "dependency", "aggregation": "sum", "visualization": "summary", "description": "Intra-batch read/write dependency edges inspected."},
            {"key": "deferred_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "OFAS cycle victims returned to the mempool before PBFT."},
            {"key": "batch_snapshot_create_ms", "type": "number", "unit": "ms", "aggregation": "sum", "visualization": "summary", "description": "Time spent creating immutable batch snapshots."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="batch_si_core_reimplementation_over_mbe_transaction_and_state_contracts",
        source={"source_type": "paper_reimplementation", "source_name": "Batch-SI: Semi-Parallel Concurrency Scheme for Permissioned Blockchains Exploiting Batch Snapshot Isolation", "reproduction_dossier": "docs/reproductions/batch_si/source_lock.md"},
    ),
    _manifest(
        "execution", "fabricpp_cg_execution", "Fabric++ Traditional CG Execution",
        "Sharma et al. SIGMOD 2019 transaction-reordering conflict-graph classifier using write-read conflicts only.",
        capabilities=["paper_baseline_fabricpp_cg", "fabricpp_read_write_conflict_definition", "tarjan_scc", "johnson_exact_cycle_enumeration", "deterministic_cycle_victim"],
        supported_backends=["real_cluster"],
        truth_boundary="fabricpp_sigmod2019_transaction_reordering_v1",
        source={"source_type": "paper_reimplementation", "source_name": "Blurring the Lines between Blockchains and Database Systems: the Case of Hyperledger Fabric", "venue": "SIGMOD 2019", "doi": "10.1145/3299869.3319883", "algorithm": "Algorithm 1 transaction reordering", "conflict_definition": "WS(Ti) intersect RS(Tj) nonempty", "reproduction_dossier": "docs/reproductions/fabricpp_cg/source_lock.md"},
    ),
    _manifest(
        "scheduler", "fabricpp_cg_scheduler", "Fabric++ Traditional CG Scheduler",
        "Builds the Fabric++ write-read conflict graph, divides it with Tarjan, enumerates all elementary cycles with Johnson, removes maximum-cycle-participation victims with lower original ordinal tie-break, and derives a serializable residual schedule.",
        capabilities=["consensus_bound_schedule", "fabricpp_read_write_conflict_definition", "no_standalone_ww_edges", "tarjan_scc", "johnson_exact_cycle_enumeration", "maximum_cycle_participation_abort", "lower_ordinal_tie_break", "serializable_schedule"],
        requirements=["execution:fabricpp_cg_execution", "block_executor:fabricpp_cg_block_executor", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="fabricpp_sigmod2019_transaction_reordering_v1",
    ),
    _manifest(
        "block_executor", "fabricpp_cg_block_executor", "Fabric++ Traditional CG Block Executor",
        "Serially materializes the consensus-bound Fabric++ Algorithm-1 order as an MBE adapter; Algorithm 1 cycle victims are terminal failed no-ops. No post-reordering parallel execution is added.",
        config={"worker_count": 1},
        schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 1, "default": 1, "readOnly": True}}),
        capabilities=["serial_paper_order_materialization", "deterministic_materialization", "fabricpp_cycle_abort_receipts", "no_cross_scheme_algorithm_reuse"],
        requirements=["execution:fabricpp_cg_execution", "scheduler:fabricpp_cg_scheduler", "routing:hash_routing_baseline", "state_access:direct_state_access", "state_storage:persistent_local_state_store", "commit:normal_commit"],
        supported_backends=["real_cluster"],
        truth_boundary="fabricpp_sigmod2019_transaction_reordering_v1",
    ),
_manifest("execution", "cg_execution", "CG / Nezha Execution", "Official-reference Nezha conventional CG classifier over the exact directed conflict multigraph.", capabilities=["paper_baseline_cg", "official_conflict_multigraph", "cycle_detection", "nezha_johnson_cycle_abort", "bounded_johnson_prefix_fallback", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_cg_official_multigraph_bounded_johnson_retry_mbe_worker_v4", source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Nezha: Exploiting Concurrency for Transaction Processing in DAG-based Blockchains", "doi": "10.1109/ICDCS54860.2022.00034", "official_repository": "CGCL-codes/Nezha", "official_commit": "85eaf541591e5f3020dd520cf3b8ee35009d296a", "reference_files": ["core/classical_graph.go", "graph/johnsonce.go", "graph/tarjanscc.go", "test.go"], "reference_scope": "conventional CG baseline shipped with the Nezha artifact", "cycle_resolution": "Tarjan SCC; complete JohnsonCE/BreakCycles while within the deterministic planning budget; if the exact cycle space exceeds that budget, MBE consumes the deterministic Johnson prefix with the same maximum-membership BreakCycles rule, removes those feedback victims, recomputes SCCs, and continues", "implementation_note": "WW parallel-arc multiplicity from NewBuildConflictGraph is preserved; bounded Johnson is an explicit scalability adaptation only for otherwise non-terminating cycle spaces; CG victims are FIFO-deferred and retried like ACG victims so fixed-workload finality requires every logical transaction to complete; BasicTopologicalSort remains reference serialization evidence; PBFT is unchanged"}),
_manifest("scheduler", "cg_scheduler", "CG / Nezha Scheduler", "Constructs Nezha NewBuildConflictGraph with official WW parallel-arc multiplicity and RW duplicate suppression; uses exact Tarjan/JohnsonCE/BreakCycles within budget and deterministic Johnson-prefix BreakCycles beyond it; cycle victims are consensus-bound Deferred retries; BasicTopologicalSort remains reference order evidence.", capabilities=["consensus_bound_schedule", "official_conflict_multigraph", "cycle_detection", "nezha_johnson_cycle_abort", "bounded_johnson_prefix_fallback", "fifo_deferred_retry_lifecycle", "basic_topological_sort_reference", "projection_validator"], requirements=["execution:cg_execution", "block_executor:cg_block_executor"], supported_backends=["real_cluster"], truth_boundary="nezha_cg_official_multigraph_bounded_johnson_retry_mbe_worker_v4"),
_manifest("block_executor", "cg_block_executor", "CG / Nezha MBE Worker Block Executor", "Executes only accepted dependency-ready frontiers from the consensus-bound Nezha-CG plan using the requested MBE worker count. Cycle victims remain algorithmic abort evidence but are non-terminal FIFO Deferred retries; no failed no-op receipt is emitted.", config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}), capabilities=["parallel_execution_adaptation", "dependency_ready_frontiers", "deterministic_materialization", "deterministic_cycle_abort_evidence", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_cg_official_multigraph_bounded_johnson_retry_mbe_worker_v4"),
    _manifest("execution", "acg_execution", "ACG / Nezha Execution", "Official-reference Nezha address-conflict-graph and hierarchical-sorting classifier; MBE retries HS-aborted logical transactions only at the experiment lifecycle layer.", capabilities=["paper_baseline_acg", "address_conflict_queues", "hierarchical_sorting", "deterministic_hs_abort_evidence", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_acg_hs_official_reference_mbe_retry_v2", source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Nezha: Exploiting Concurrency for Transaction Processing in DAG-based Blockchains", "doi": "10.1109/ICDCS54860.2022.00034", "official_repository": "CGCL-codes/Nezha", "implementation_note": "CreateGraph -> QueuesSort -> DeSS is unchanged; HS abort -> FIFO Deferred retry is an MBE experiment-lifecycle adaptation, not a claim about the Nezha reference benchmark"}),
    _manifest("scheduler", "acg_scheduler", "ACG / Nezha Scheduler", "Runs one first-pass Nezha CreateGraph -> QueuesSort -> DeSS plan, consensus-binds the accepted/deferred projection, and returns HS victims through the existing FIFO Deferred path.", capabilities=["consensus_bound_schedule", "address_conflict_queues", "hierarchical_sorting", "deterministic_hs_abort_evidence", "fifo_deferred_retry_lifecycle"], requirements=["execution:acg_execution", "block_executor:acg_block_executor"], supported_backends=["real_cluster"], truth_boundary="nezha_acg_hs_official_reference_mbe_retry_v2"),
    _manifest("block_executor", "acg_block_executor", "ACG / Nezha Block Executor", "Executes only the consensus-bound accepted Nezha HS waves; HS victims stay non-terminal and retry in a later block while abort evidence remains exported.", config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}), capabilities=["parallel_execution", "deterministic_materialization", "deterministic_hs_abort_evidence", "fifo_deferred_retry_lifecycle"], supported_backends=["real_cluster"], truth_boundary="nezha_acg_hs_official_reference_mbe_retry_v2"),
    _manifest("execution", "bsx_execution", "BSX Execution", "Batch-Schedule-Execute conflict-graph coloring classifier.", capabilities=["paper_baseline_bsx", "undirected_conflict_graph"], supported_backends=["real_cluster"], truth_boundary="bsx_homogeneous_conflict_graph_coloring_dsatur_v1", source={"source_type": "paper_reimplementation", "source_name": "Batch-Schedule-Execute: On Optimizing Concurrent Deterministic Scheduling for Blockchains", "doi": "10.1109/SRDS64841.2024.00025", "arxiv": "2402.05535"}),
    _manifest("scheduler", "bsx_scheduler", "BSX Scheduler", "Builds an undirected conflict graph and applies deterministic DSATUR coloring for the homogeneous-transaction scheduling case.", capabilities=["consensus_bound_schedule", "undirected_conflict_graph", "deterministic_dsatur_coloring"], requirements=["execution:bsx_execution", "block_executor:bsx_block_executor"], supported_backends=["real_cluster"], truth_boundary="bsx_homogeneous_conflict_graph_coloring_dsatur_v1"),
    _manifest("block_executor", "bsx_block_executor", "BSX Block Executor", "Executes one independent color class in parallel before advancing to the next color.", config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}), capabilities=["parallel_execution", "deterministic_materialization"], supported_backends=["real_cluster"], truth_boundary="bsx_homogeneous_conflict_graph_coloring_dsatur_v1"),
    _manifest("state_access", "direct_state_access", "Direct State Access", "Direct deterministic state database access."),
    _manifest("state_access", "metatrack_local_exact_access", "MetaTrack Local Exact Access", "MetaTrack exact-version access policy with execution-domain local handoff first and Home fallback.", capabilities=["metatrack_exact_version", "local_exact_handoff", "home_fallback"]),
    _manifest("state_access", "metatrack_home_exact_access", "MetaTrack Home Exact Access", "MetaTrack exact-version access policy forcing publication/fetch through the persistent Home while retaining prefetch, batching and Version Liveness.", capabilities=["metatrack_exact_version", "home_exact_only"]),
    _manifest("state_storage", "persistent_local_state_store", "Persistent Local State Store", "Per-node persisted state, block, receipt, and transaction index files.", capabilities=["persistent_state", "state_root"]),
    _manifest("cross_shard", "relay_certificate_protocol", "Relay Certificate Cross-shard", "SourceLock, relay certificate, target commit, source finalization, and timeout/refund evidence.", capabilities=["cross_shard", "relay_certificate"]),
    _manifest("commit", "normal_commit", "Normal Commit", "Durable deterministic commit."),
    _manifest("commit", "commutative_hot_update_aggregation", "Commutative Hot-update Aggregation", "Commit profile that records aggregation decisions for hot updates.", aliases=["aggregation"]),
    _manifest("fault_injection", "faults_disabled", "Faults Disabled", "No network fault policy."),
    _manifest("fault_injection", "network_delay_drop", "Network Delay and Drop", "Deterministic real TCP delay/drop policy.", config={"delay_ms": 5, "drop_every": 0}, schema=_schema({"delay_ms": {"type": "integer", "minimum": 0, "maximum": 1000, "default": 5}, "drop_every": {"type": "integer", "minimum": 0, "maximum": 10000, "default": 0}})),
    _manifest("metrics", "runtime_core_metrics", "Runtime Core Metrics", "Runtime counters and state-root summaries.", metrics=[{"key": "committed_block_count", "type": "integer", "unit": "block", "aggregation": "sum", "visualization": "summary", "description": "Committed blocks."}, {"key": "state_root_consistent", "type": "ratio", "unit": "boolean", "aggregation": "all", "visualization": "summary", "description": "Validator roots agree within every shard."}]),
    _manifest("observability", "node_network_consensus_observer", "Node, Network, and Consensus Observer", "Node logs, TCP logs, consensus logs, and artifact catalog."),
    # MBE_CALVIN_DUAL_REPRO_V2_20260923: paper-locked Calvin baseline plus explicit stateless adaptation.
    _manifest("transaction_admission", "calvin_declared_access_admission", "Calvin Declared-access Admission", "Requires a signed complete AccessList before deterministic scheduling.", requirements=["static_read_write_set"], capabilities=["calvin_static_access"], source={"type": "paper_and_official_source_reimplementation", "paper": "Calvin: Fast Distributed Transactions for Partitioned Database Systems (SIGMOD 2012)", "repository": "https://github.com/yaledb/calvin", "repository_commit": "c1fb1a51584bb150a1c1e493469bd2d7ac0ff40a", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("routing", "calvin_global_routing", "Calvin Global Ordering Routing", "One MBE PBFT ordering domain with partitioned Calvin state/execution homes.", capabilities=["calvin_global_ordering", "stateful_partitioned_execution"], source={"type": "paper_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("routing", "stateless_calvin_global_routing", "Stateless Calvin Global Ordering Routing", "Global Calvin order for the stateless compatibility profile; MetaTrack control-plane capabilities are intentionally absent.", capabilities=["calvin_global_ordering", "stateless_calvin_adaptation"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("execution", "calvin_execution", "Calvin Deterministic Execution", "Executes transactions in the PBFT-bound global serial order after deterministic locks become ready.", capabilities=["deterministic_serial_equivalence", "no_conflict_abort"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("scheduler", "calvin_deterministic_scheduler", "Calvin Deterministic Lock Scheduler", "Per-key FIFO S/X lock queues with transaction wait counters and ready-queue wakeups.", capabilities=["fifo_shared_exclusive_locking", "global_order_determinism"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("scheduler", "stateless_calvin_deterministic_scheduler", "Stateless Calvin Consensus-Version Scheduler", "Calvin FIFO deterministic scheduling plus a PBFT-bound exact-version plan derived from final block order; used only by Stateless Calvin.", capabilities=["fifo_shared_exclusive_locking", "global_order_determinism", "consensus_bound_version_plan"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("block_executor", "calvin_block_executor", "Calvin Block Executor", "Stateful partition-resident Calvin execution with READ_RESULT forwarding and local-write ownership.", config={"worker_count": 4, "read_result_timeout_ms": 0, "outcome_timeout_ms": 0}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "read_result_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}, "outcome_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}}), capabilities=["calvin_read_result", "calvin_outcome_harmonization", "partition_resident_state", "no_2pc"], metrics=[{"key": "calvin_lock_wait_count", "type": "integer", "unit": "event", "aggregation": "sum", "visualization": "summary", "description": "Deterministic lock waits."}, {"key": "calvin_remote_read_count", "type": "integer", "unit": "read", "aggregation": "sum", "visualization": "summary", "description": "Remote READ_RESULT values consumed."}], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("block_executor", "stateless_calvin_block_executor", "Stateless Calvin Block Executor", "Compatibility adaptation that physically fetches signed-AccessList values from deterministic state homes after Calvin lock readiness and writes produced values back to those persistent homes.", config={"worker_count": 4, "read_result_timeout_ms": 0, "outcome_timeout_ms": 0}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "read_result_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}, "outcome_timeout_ms": {"type": "integer", "minimum": 0, "maximum": 600000, "default": 0}}), capabilities=["calvin_outcome_harmonization", "stateless_calvin_adaptation", "physical_remote_state_fetch", "physical_remote_state_writeback", "exact_state_version_fetch", "consensus_bound_version_plan", "block_start_committed_value", "no_2pc", "no_metatrack_state_ready"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("state_access", "calvin_partition_state_access", "Calvin Partition State Access", "Partition-resident state reads plus Calvin READ_RESULT forwarding.", capabilities=["calvin_partition_resident_state"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("state_access", "stateless_calvin_state_access", "Stateless Calvin State Access", "Physical deterministic state-home access used only by the Stateless Calvin adaptation; predecessor/producer versions are bound to the PBFT-bound final candidate Calvin block order.", capabilities=["declared_state_projection", "signed_access_projection", "remote_state_fetch", "remote_state_writeback", "exact_state_version_fetch", "consensus_bound_version_plan"], source={"type": "compatibility_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("state_storage", "calvin_partition_state_store", "Calvin Partition State Store", "Persists state by ExecutionShardID while the PBFT ShardID remains one global ordering domain.", capabilities=["execution_shard_storage_identity", "persistent_partition_state"], source={"type": "mbe_platform_adaptation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    _manifest("cross_shard", "calvin_no_2pc_coordinator", "Calvin Participant Protocol", "Disables MBE Relay/Finalize and traditional 2PC; distributed reads use Calvin READ_RESULT.", capabilities=["calvin_read_result", "no_2pc", "no_legacy_relay"], source={"type": "paper_reimplementation", "dossier": "docs/reproductions/calvin/source_lock.md"}),
    # MBE_OPTME_TXALLO_BASELINES_20260928: post-consensus OptME and history-only TxAllo baselines.
    _manifest(
        "execution", "optme_execution", "OptME Post-consensus Execution",
        "Classifies the SC'24 OptME path. OptME consumes PBFT consensus output, simulates transactions, constructs an address/state-key conflict graph, hierarchically schedules, reorders eligible write-only aborts, and re-executes remaining aborted groups.",
        capabilities=["post_consensus_simulation", "observed_rw_set", "optme_address_conflict_graph"],
        requirements=["scheduler:optme_scheduler"], supported_backends=["real_cluster"],
        truth_boundary="optme_author_source_4cac103_post_consensus_simulate_acg_schedule_v1",
        source={"source_type": "paper_and_official_source_reimplementation", "source_name": "Toward High-Performance Blockchain System by Blurring the Line between Ordering and Execution", "venue": "SC 2024", "repository": "https://github.com/Dong-Hyeon-Yu/optme", "repository_commit": "4cac103bd98440670d71219dfa185b8516ea6512", "reproduction_dossier": "docs/reproductions/optme/source_lock.md"},
    ),
    _manifest(
        "scheduler", "optme_scheduler", "OptME Observed-RW Scheduler",
        "Implements the author-source AddressBasedConflictGraph ordering: address rank by in-degree/out-degree/address, First-Updater-Wins early abort, write-only reordering, sequence extraction, and aborted-transaction rescheduling epochs.",
        capabilities=["optme_hierarchical_sort", "first_updater_wins", "optme_reorder", "optme_reschedule_epochs"],
        requirements=["execution:optme_execution"], supported_backends=["real_cluster"],
        truth_boundary="optme_author_address_based_conflict_graph_4cac103_v1",
        source={"source_type": "official_source_reimplementation", "repository": "https://github.com/Dong-Hyeon-Yu/optme", "repository_commit": "4cac103bd98440670d71219dfa185b8516ea6512", "reproduction_dossier": "docs/reproductions/optme/source_lock.md"},
    ),
    _manifest(
        "block_executor", "optme_block_executor", "OptME Block Executor",
        "Stateful OptME: after PBFT, simulates all transactions against one block-start snapshot, schedules from observed read/write sets, commits the author-source sequence plan, and performs the source second-pass re-execution/validation path.",
        config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}),
        capabilities=["parallel_simulation", "optme_schedule_commit", "optme_second_pass_validation"],
        requirements=["execution:optme_execution", "scheduler:optme_scheduler", "routing:hash_routing_baseline", "consensus:pbft_style_consensus"], supported_backends=["real_cluster"],
        metrics=[{"key": "optme_simulation_ms", "type": "integer", "unit": "ms", "aggregation": "sum", "visualization": "summary", "description": "Post-consensus OptME simulation time."}, {"key": "optme_early_abort_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions assigned to OptME's aborted/reschedule path."}],
        truth_boundary="optme_author_source_4cac103_stateful_per_pbft_shard_mbe_multishard_integration_v3",
        source={"source_type": "paper_and_official_source_reimplementation", "repository": "https://github.com/Dong-Hyeon-Yu/optme", "repository_commit": "4cac103bd98440670d71219dfa185b8516ea6512", "reproduction_dossier": "docs/reproductions/optme/source_lock.md"},
    ),
    _manifest(
        "routing", "stateless_optme_routing", "Stateless-OptME State Projection Routing",
        "Stateless compatibility routing. Signed AccessList data is used only to materialize the block-start state projection; OptME still derives its scheduling read/write sets from actual post-consensus simulation.",
        capabilities=["stateless_direct_execution", "signed_access_projection", "batch_routing_control_plane", "exact_state_version_transport", "no_metatrack_frontier"],
        requirements=["block_executor:stateless_optme_block_executor"], supported_backends=["real_cluster"],
        truth_boundary="stateless_optme_accesslist_projection_plus_global_exact_version_transport_v2",
        source={"source_type": "compatibility_adaptation", "reproduction_dossier": "docs/reproductions/optme/mbe_mapping.md"},
    ),
    _manifest(
        "block_executor", "stateless_optme_block_executor", "Stateless-OptME Block Executor",
        "Runs the same OptME scheduling core as OptME over each MBE PBFT shard consensus output with a signed-AccessList-bounded remote block-start state projection. The AccessList is never substituted for the observed simulation read/write set; multi-shard operation is an explicit MBE adaptation, not an OptME paper contribution.",
        config={"worker_count": 4}, schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}),
        capabilities=["parallel_simulation", "optme_schedule_commit", "stateless_projection", "physical_remote_state_fetch", "physical_remote_state_writeback", "exact_state_version_transport", "preserve_optme_scheduler"],
        requirements=["routing:stateless_optme_routing", "execution:optme_execution", "scheduler:optme_scheduler", "consensus:pbft_style_consensus"], supported_backends=["real_cluster"],
        truth_boundary="stateless_optme_same_core_exact_version_transport_per_pbft_shard_v3",
        source={"source_type": "compatibility_adaptation", "reproduction_dossier": "docs/reproductions/optme/mbe_mapping.md"},
    ),
    _manifest(
        "sharding", "txallo_account_sharding", "TxAllo Account Allocation",
        "TxAllo ICDE'23 account allocation. Builds an undirected weighted account transaction graph from pre-evaluation committed-history records only, runs G-TxAllo initialization and A-TxAllo historical updates, then freezes the account-to-shard mapping for the measured window.",
        config={"eta": 2.0, "lambda": 0.0, "epsilon": 0.0, "history_records": 5000, "adaptive_chunk_records": 500},
        schema=_schema({"eta": {"type": "number", "minimum": 1.000001, "maximum": 100, "default": 2.0}, "lambda": {"type": "number", "minimum": 0, "default": 0.0}, "epsilon": {"type": "number", "minimum": 0, "default": 0.0}, "history_records": {"type": "integer", "minimum": 1, "maximum": 1000000, "default": 5000}, "adaptive_chunk_records": {"type": "integer", "minimum": 1, "maximum": 100000, "default": 500}}),
        capabilities=["txallo_account_graph", "g_txallo", "a_txallo", "pre_evaluation_history_only", "frozen_evaluation_mapping"], supported_backends=["real_cluster"],
        truth_boundary="txallo_icde2023_algorithm1_2_account_graph_frozen_pre_evaluation_history_v1",
        source={"source_type": "paper_reimplementation", "source_name": "TxAllo: Dynamic Transaction Allocation in Sharded Blockchain Systems", "venue": "ICDE 2023", "arxiv": "2212.11584", "repository": "https://github.com/zhangyuanzhe1996/TxAllo", "repository_note": "public repository reviewed but no usable algorithm implementation was present; paper formulas and Algorithms 1/2 are the source of truth", "reproduction_dossier": "docs/reproductions/txallo/source_lock.md"},
    ),
    _manifest(
        "routing", "txallo_routing", "TxAllo Transaction Routing",
        "Routes each transaction according to the frozen TxAllo sender/receiver account allocation. It consumes the sharding plugin mapping and never updates that mapping from the same pending evaluation batch.",
        capabilities=["txallo_frozen_mapping_routing", "stateful_local_execution", "no_future_batch_training"], requirements=["sharding:txallo_account_sharding"], supported_backends=["real_cluster"],
        truth_boundary="txallo_frozen_mapping_stateful_route_v1", source={"source_type": "paper_reimplementation", "reproduction_dossier": "docs/reproductions/txallo/mbe_mapping.md"},
    ),
    _manifest(
        "routing", "stateless_txallo_routing", "Stateless-TxAllo Transaction Routing",
        "Uses exactly the same frozen TxAllo account allocation as TxAllo while opting into MBE's generic stateless direct execution and remote state projection/writeback infrastructure.",
        capabilities=["txallo_frozen_mapping_routing", "stateless_direct_execution", "batch_routing_control_plane", "exact_state_version_transport", "preserve_txallo_fifo_scheduler", "no_metatrack_frontier"], requirements=["sharding:txallo_account_sharding"], supported_backends=["real_cluster"],
        truth_boundary="stateless_txallo_same_mapping_exact_version_state_substrate_v2", source={"source_type": "compatibility_adaptation", "reproduction_dossier": "docs/reproductions/txallo/mbe_mapping.md"},
    ),
    # MBE_PORYGON_PAPER_REPRO_20260921_V8_REFACTOR: Porygon v8 single-ordering-domain / logical-ESC reimplementation.
    _manifest(
        "routing", "porygon_stateless_routing", "Porygon Stateless Ordering-domain Routing",
        "Routes every Porygon transaction into one physical MBE/PBFT ordering domain. Logical execution sharding is owned by the Porygon consensus-bound ESC plan, not MBE BatchRouting.",
        capabilities=["single_physical_ordering_domain", "signed_access_plan_binding", "no_meta_remote_state_control_plane"],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_single_physical_ordering_domain_logical_esc_v2",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "block_producer", "porygon_transaction_block_producer", "Porygon Transaction Block Producer",
        "Builds a Transaction Block, selects a deterministic EC Witness Committee, collects authenticated witness votes to the configured/fault-derived threshold, and binds the resulting Witness Certificate before PBFT ordering.",
        config={"block_size": 100, "interval_ms": 75, "witness_threshold": 1},
        schema=_schema({"block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "transaction_block_size": {"type": "integer", "minimum": 10, "maximum": 5000, "default": 100}, "interval_ms": {"type": "integer", "minimum": 25, "maximum": 5000, "default": 75}, "witness_threshold": {"type": "integer", "minimum": 1, "maximum": 1024, "default": 1}}),
        capabilities=["porygon_transaction_block", "transaction_root", "signed_access_root", "ec_witness_certificate", "witness_threshold_enforced", "proposal_evidence"],
        requirements=["routing:porygon_stateless_routing", "scheduler:porygon_pipeline_scheduler", "block_executor:porygon_block_executor"],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_real_ec_witness_certificate_v4;tw_runtime_minimum_f_plus_one;pbft_algorithm_unchanged",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "execution", "porygon_execution", "Porygon Execution Classifier",
        "Execution classification for globally ordered transactions assigned to dynamically sorted EC/ESC roles using the Porygon account/object state-owner mapping.",
        capabilities=["porygon_global_order", "execution_subcommittee", "dynamic_esc_role", "account_object_owner_partition"], supported_backends=["real_cluster"],
        truth_boundary="porygon_global_order_dynamic_esc_single_execution_v3;deterministic_vrf_style_sortition_adapter",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "scheduler", "porygon_pipeline_scheduler", "Porygon 3D Parallelism Planner",
        "Binds Witness evidence, initiating-account/object state-owner ESC assignments, and consensus-bound execution plans, then drives the Porygon-only cross-height W/O/E/M lifecycle with ordered/executed/protocol-committed cursors, cross-round Pending CTx conflict evidence, and following-ESC update handoff while PBFT itself remains unchanged.",
        config={"execution_shard_count": 4, "execution_committee_count": 3, "pipeline_enabled": True, "cross_batch_witness": True},
        schema=_schema({"execution_shard_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "execution_committee_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 3}, "pipeline_enabled": {"type": "boolean", "default": True}, "cross_batch_witness": {"type": "boolean", "default": True}}),
        capabilities=["porygon_cross_height_woem_pipeline", "cross_round_pending_ctx", "following_esc_update_handoff", "explicit_rollback_certificate", "porygon_witness_order_execute_commit", "real_cross_batch_witness_overlap", "dynamic_execution_subcommittee_sharding", "account_object_state_owner", "oc_cross_esc_conflict_abandonment", "consensus_bound_execution_plan", "single_esc_cross_shard_execution"],
        requirements=["routing:porygon_stateless_routing", "block_producer:porygon_transaction_block_producer", "execution:porygon_execution", "block_executor:porygon_block_executor", "state_access:porygon_remote_state_access", "cross_shard:porygon_cross_shard_coordinator", "consensus:pbft_style_consensus"],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_paper_fidelity_plan_v5;cross_batch_witness_has_real_wall_clock_overlap;shared_pbft_ordering_heights_remain_sequential_mbe_adaptation",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "block_executor", "porygon_block_executor", "Porygon ESC Batch Executor",
        "Executes each dynamic ESC's complete assigned batch using local conflict lanes, returns one authenticated batch result per ESC, enforces Te=f+1, and performs explicit OC-coordinated Multi-Shard Update before partition materialization.",
        config={"worker_count": 4, "execution_shard_count": 4, "execution_committee_count": 3, "pipeline_enabled": True, "cross_batch_witness": True, "require_distributed_esc": False},
        schema=_schema({"worker_count": {"type": "integer", "minimum": 1, "maximum": 32, "default": 4}, "execution_shard_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}, "execution_committee_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 3}, "pipeline_enabled": {"type": "boolean", "default": True}, "cross_batch_witness": {"type": "boolean", "default": True}, "require_distributed_esc": {"type": "boolean", "default": False}}),
        capabilities=["porygon", "dynamic_execution_subcommittee", "esc_batch_result_certificate", "execution_threshold_f_plus_one", "single_execution_cross_shard", "verified_state_proof", "explicit_multi_shard_update", "multi_shard_majority_root_certificate", "execution_plan_digest", "no_meta_remote_state_control_plane"],
        requirements=["scheduler:porygon_pipeline_scheduler", "execution:porygon_execution", "routing:porygon_stateless_routing", "state_access:porygon_remote_state_access", "consensus:pbft_style_consensus"],
        metrics=[
            {"key": "porygon_witnessed_block_count", "type": "integer", "unit": "block", "aggregation": "sum", "visualization": "summary", "description": "Transaction blocks carrying a verified EC Witness Certificate."},
            {"key": "porygon_execution_shard_count", "type": "integer", "unit": "shard", "aggregation": "max", "visualization": "summary", "description": "Configured Porygon ESC count."},
            {"key": "porygon_active_execution_shard_count", "type": "integer", "unit": "shard", "aggregation": "max", "visualization": "summary", "description": "ESC roles that executed at least one transaction."},
            {"key": "porygon_cross_shard_transaction_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Transactions whose Porygon protocol state ownership spans multiple StateOwner partitions."},
            {"key": "porygon_single_shard_execution_count", "type": "integer", "unit": "tx", "aggregation": "sum", "visualization": "summary", "description": "Cross-shard transactions executed by exactly one ESC before Multi-Shard Update."},
            {"key": "maximum_parallel_width", "type": "integer", "unit": "tx", "aggregation": "max", "visualization": "summary", "description": "Maximum observed concurrent ESC-local business execution width."},
        ],
        supported_backends=["real_cluster"],
        truth_boundary="porygon_esc_batch_result_certificate_plus_explicit_multishard_update_v5;no_per_wave_network_certificate_in_production",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "state_storage", "porygon_partition_state_store", "Porygon Co-located Storage Role",
        "Stores only the fixed state partition owned by this node's Storage Role. Storage and consensus remain logically separated while roles are co-located on existing MBE machines for resource-fair experiments.",
        capabilities=["persistent_state", "state_root", "execution_shard_storage_identity", "porygon_storage_consensus_role_separation", "merkle_treap_state_proof"],
        requirements=["routing:porygon_stateless_routing"], supported_backends=["real_cluster"],
        truth_boundary="porygon_storage_role_colocation_on_existing_mbe_nodes_v2;no_extra_physical_storage_nodes",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "state_access", "porygon_remote_state_access", "Porygon Verified State Projection",
        "Fetches only signed AccessList state from its Porygon StateOwner home and verifies a Merkle-treap inclusion or non-membership proof against the returned authenticated partition root before business execution.",
        capabilities=["signed_access_projection", "fail_closed_access_closure", "physical_state_fetch", "verified_merkle_treap_inclusion_nonmembership_proof", "verified_merkle_treap_proof", "storage_consensus_role_separation"],
        requirements=["routing:porygon_stateless_routing"], supported_backends=["real_cluster"],
        truth_boundary="porygon_signed_access_projection_with_verified_state_proof_v5;storage_roles_colocated_on_existing_nodes",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),
    _manifest(
        "cross_shard", "porygon_cross_shard_coordinator", "Porygon Multi-Shard Update Coordinator",
        "Uses Single-Shard Execution followed by explicit OC Multi-Shard Update requests, strict-majority state-root ACK certificates, bounded retry and rollback; it never activates MBE's generic Relay/Finalize protocol.",
        config={"execution_shard_count": 4}, schema=_schema({"execution_shard_count": {"type": "integer", "minimum": 1, "maximum": 64, "default": 4}}),
        capabilities=["porygon_oc_conflict_control", "single_esc_execution", "explicit_multi_shard_update", "strict_majority_update_ack", "bounded_retry", "rollback", "global_state_root_aggregation", "physical_relay_disabled"],
        requirements=["routing:porygon_stateless_routing", "block_executor:porygon_block_executor"], supported_backends=["real_cluster"],
        truth_boundary="porygon_explicit_multi_shard_update_state_machine_v5;generic_mbe_relay_finalize_disabled",
        source={"source_type": "paper_reimplementation", "source_name": "Porygon: Scaling Blockchain via 3D Parallelism", "doi": "10.1109/ICDE60146.2024.00153", "reproduction_dossier": "docs/reproductions/porygon/source_lock.md"},
    ),

]


class PluginManifestStore:
    def __init__(self, manifests: Iterable[V5PluginManifest] = _MANIFESTS):
        self._items = list(manifests)
        seen: set[tuple[str, str, str]] = set()
        for item in self._items:
            if item.category not in CATEGORIES:
                raise ValueError(f"unknown plugin category: {item.category}")
            key = (item.plugin_id, item.category, item.version)
            if key in seen:
                raise ValueError(f"duplicate plugin manifest: {item.plugin_id}")
            seen.add(key)

    def list(self) -> list[V5PluginManifest]:
        return list(self._items)

    def get(self, plugin_id: str) -> V5PluginManifest:
        for item in self._items:
            if item.plugin_id == plugin_id or plugin_id in item.legacy_aliases:
                return item
        raise ValueError(f"unknown plugin: {plugin_id}")


STORE = PluginManifestStore()
