package main
import("encoding/json";"fmt";"github.com/hyperledger/fabric-contract-api-go/contractapi")
type AssetContract struct{ contractapi.Contract }
func assetKey(id string)string{return "asset:"+id}; func balanceKey(id string)string{return "balance:"+id}
func (c *AssetContract) CreateAsset(ctx contractapi.TransactionContextInterface,id,owner,metadata string)error{ b,_:=ctx.GetStub().GetState(assetKey(id));if b!=nil{return fmt.Errorf("asset exists")}; v,_:=json.Marshal(Asset{id,owner,metadata,1,""});return ctx.GetStub().PutState(assetKey(id),v) }
func (c *AssetContract) TransferAsset(ctx contractapi.TransactionContextInterface,asset_id,from,to string)error{a,e:=c.ReadAsset(ctx,asset_id);if e!=nil||a.Owner!=from{return fmt.Errorf("owner mismatch")};a.Owner=to;a.Version++;b,_:=json.Marshal(a);if e=ctx.GetStub().PutState(assetKey(asset_id),b);e!=nil{return e};return c.emit(ctx,"AssetTransferred",map[string]any{"tx_type":"asset_transfer","contract":"asset","function":"TransferAsset","args":map[string]string{"asset_id":asset_id,"from":from,"to":to},"primary_key":assetKey(asset_id),"access_keys":[]string{assetKey(asset_id)},"event":"AssetTransferred"})}
func (c *AssetContract) TradeAsset(ctx contractapi.TransactionContextInterface,asset_id,seller,buyer string,price int)error{a,e:=c.ReadAsset(ctx,asset_id);if e!=nil||a.Owner!=seller{return fmt.Errorf("owner mismatch")};bb,e:=c.GetBalance(ctx,buyer);if e!=nil||bb.Amount<price{return fmt.Errorf("insufficient balance")};sb,e:=c.GetBalance(ctx,seller);if e!=nil{return e};bb.Amount-=price;sb.Amount+=price;a.Owner=buyer;a.Version++;for _,v:=range []struct{k string;v any}{{assetKey(asset_id),a},{balanceKey(buyer),bb},{balanceKey(seller),sb}}{b,_:=json.Marshal(v.v);if e=ctx.GetStub().PutState(v.k,b);e!=nil{return e}};return c.emit(ctx,"AssetTraded",map[string]any{"tx_type":"asset_trade","contract":"asset","function":"TradeAsset","args":map[string]any{"asset_id":asset_id,"seller":seller,"buyer":buyer,"price":price},"primary_key":assetKey(asset_id),"access_keys":[]string{assetKey(asset_id),balanceKey(seller),balanceKey(buyer)},"event":"AssetTraded"})}
func(c *AssetContract) ReadAsset(ctx contractapi.TransactionContextInterface,id string)(*Asset,error){b,e:=ctx.GetStub().GetState(assetKey(id));if e!=nil||b==nil{return nil,fmt.Errorf("asset missing")};var a Asset;e=json.Unmarshal(b,&a);return &a,e};func(c *AssetContract)GetBalance(ctx contractapi.TransactionContextInterface,id string)(*Balance,error){b,e:=ctx.GetStub().GetState(balanceKey(id));if e!=nil||b==nil{return nil,fmt.Errorf("balance missing")};var v Balance;e=json.Unmarshal(b,&v);return &v,e};func(c *AssetContract)SetBalance(ctx contractapi.TransactionContextInterface,id string,amount int)error{b,_:=json.Marshal(Balance{id,amount});return ctx.GetStub().PutState(balanceKey(id),b)};func(c *AssetContract)InitLedger(ctx contractapi.TransactionContextInterface)error{return nil}
func(c *AssetContract)emit(ctx contractapi.TransactionContextInterface,name string,p any)error{b,_:=json.Marshal(p);return ctx.GetStub().SetEvent(name,b)}
