package main
import("encoding/json";"fmt";"github.com/hyperledger/fabric-contract-api-go/contractapi")
type AssetContract struct{ contractapi.Contract }
func assetKey(id string)string{return "asset:"+id}; func balanceKey(id string)string{return "balance:"+id}
func (c *AssetContract) CreateAsset(ctx contractapi.TransactionContextInterface,id,owner,metadata string)error{ b,_:=ctx.GetStub().GetState(assetKey(id));if b!=nil{return fmt.Errorf("asset exists")}; v,_:=json.Marshal(Asset{id,owner,metadata,1,""});return ctx.GetStub().PutState(assetKey(id),v) }
func (c *AssetContract) TransferAsset(ctx contractapi.TransactionContextInterface,asset_id,from,to string)error{return c.emit(ctx,"AssetTransferred",map[string]any{"tx_type":"asset_transfer","contract":"asset","function":"TransferAsset","args":map[string]string{"asset_id":asset_id,"from":from,"to":to},"primary_key":assetKey(asset_id),"access_keys":[]string{assetKey(asset_id)},"event":"AssetTransferred"})}
func (c *AssetContract) TradeAsset(ctx contractapi.TransactionContextInterface,asset_id,seller,buyer string,price int)error{return c.emit(ctx,"AssetTraded",map[string]any{"tx_type":"asset_trade","contract":"asset","function":"TradeAsset","args":map[string]any{"asset_id":asset_id,"seller":seller,"buyer":buyer,"price":price},"primary_key":assetKey(asset_id),"access_keys":[]string{assetKey(asset_id),balanceKey(seller),balanceKey(buyer)},"event":"AssetTraded"})}
func(c *AssetContract) ReadAsset(ctx contractapi.TransactionContextInterface,id string)(*Asset,error){return nil,nil};func(c *AssetContract)GetBalance(ctx contractapi.TransactionContextInterface,id string)(*Balance,error){return nil,nil};func(c *AssetContract)SetBalance(ctx contractapi.TransactionContextInterface,id string,amount int)error{return nil};func(c *AssetContract)InitLedger(ctx contractapi.TransactionContextInterface)error{return nil}
func(c *AssetContract)emit(ctx contractapi.TransactionContextInterface,name string,p any)error{b,_:=json.Marshal(p);return ctx.GetStub().SetEvent(name,b)}
