import { useEffect, useMemo, useState } from "react";

import { compileV5ExperimentSpec, createV3SavedConfig, fetchV5PluginCatalog, runV5RealCluster, validateV5ExperimentSpec, type V5CompatibilityResult, type V5ExperimentSpec, type V5PluginManifest, type V5PluginSelection, type V5SchemaField } from "../../api";

const categoryLabels: Record<string, string> = { workload: "Workload", transaction_admission: "Admission", txpool: "TxPool", sharding: "Sharding", routing: "Routing", block_producer: "Block producer", consensus: "Consensus", network: "Network", execution: "Execution", scheduler: "Scheduler", state_access: "State access", state_storage: "State storage", cross_shard: "Cross-shard", commit: "Commit", fault_injection: "Fault injection", metrics: "Metrics", observability: "Observability" };

export default function RealClusterWorkbench() {
  const [catalog, setCatalog] = useState<V5PluginManifest[]>([]);
  const [selections, setSelections] = useState<V5PluginSelection[]>([]);
  const [topology, setTopology] = useState({ nodes: 8, shards: 2, validators_per_shard: 4 });
  const [txCount, setTxCount] = useState(100);
  const [seed, setSeed] = useState(7);
  const [duration, setDuration] = useState(6000);
  const [compatibility, setCompatibility] = useState<V5CompatibilityResult | null>(null);
  const [compiled, setCompiled] = useState<Record<string, unknown> | null>(null);
  const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);

  const categories = useMemo(() => Array.from(new Set(catalog.map((item) => item.category))), [catalog]);
  const spec: V5ExperimentSpec = { name: "v5_real_cluster_validation", execution_backend: "real_cluster", plugin_selections: selections, topology, tx_count: txCount, seed, duration_ms: duration, fault_policy: { mode: selectionFor("fault_injection")?.plugin_id === "faults_disabled" ? "disabled" : "network_delay_drop" } };

  useEffect(() => { void load(); }, []);
  async function load() { try { const items = await fetchV5PluginCatalog("real_cluster"); setCatalog(items); setSelections(defaultSelections(items)); } catch (error) { setMessage(String(error)); } }
  function selectionFor(category: string) { return selections.find((item) => item.category === category); }
  function choose(category: string, plugin: V5PluginManifest) { setSelections((current) => [...current.filter((item) => item.category !== category), { category, plugin_id: plugin.plugin_id, config: { ...plugin.default_config } }]); setCompatibility(null); setCompiled(null); }
  function updateConfig(category: string, key: string, value: unknown) { setSelections((current) => current.map((item) => item.category === category ? { ...item, config: { ...item.config, [key]: value } } : item)); setCompatibility(null); setCompiled(null); }
  async function validate() { setBusy(true); try { const response = await validateV5ExperimentSpec(spec); setCompatibility(response); setMessage(response.valid ? "Compatibility validation passed." : "Compatibility validation found blockers."); } catch (error) { setMessage(String(error)); } finally { setBusy(false); } }
  async function compile() { setBusy(true); try { const response = await compileV5ExperimentSpec(spec); setCompiled(response); setMessage("Immutable V5 CompiledRunPlan generated."); } catch (error) { setMessage(String(error)); } finally { setBusy(false); } }
  async function saveTemplate() { setBusy(true); try { const saved = await createV3SavedConfig({ config_kind: "method", name: "V5 real-cluster method", tags: ["v5", "real_cluster"], validation_status: compatibility?.valid ? "runnable" : "valid", payload: { schema_version: "v5_plugin_profile_v1", plugin_selections: selections, plugin_parameters: selections, compatibility_snapshot: compatibility, source_composer_draft: {} } }); setMessage(`Saved through V3SavedConfig: ${saved.config_id}`); } catch (error) { setMessage(String(error)); } finally { setBusy(false); } }
  async function run() { setBusy(true); try { const response = await runV5RealCluster(spec); setResult(response.summary); setMessage(`Real cluster ${response.status}: ${response.run_id}`); } catch (error) { setMessage(String(error)); } finally { setBusy(false); } }

  return <section className="page-grid">
    <article className="final-card wide page-hero"><p className="eyebrow">V5.1 Real Cluster</p><h2>插件驱动真实多进程运行</h2><p>该页从 Catalog 和 Schema 动态渲染。Real Cluster 失败会直接失败，不会回退到 Simulation 或 V4 smoke。</p>{message && <p className="notice">{message}</p>}</article>
    <article className="final-card wide"><h3>ExperimentSpec</h3><div className="experiment-condition-grid"><label><span>nodes</span><input type="number" min={1} max={16} value={topology.nodes} onChange={(event) => setTopology({ ...topology, nodes: Number(event.target.value) })} /></label><label><span>shards</span><input type="number" min={1} max={4} value={topology.shards} onChange={(event) => setTopology({ ...topology, shards: Number(event.target.value) })} /></label><label><span>validators/shard</span><input type="number" min={1} max={16} value={topology.validators_per_shard} onChange={(event) => setTopology({ ...topology, validators_per_shard: Number(event.target.value) })} /></label><label><span>tx_count</span><input type="number" min={1} max={10000} value={txCount} onChange={(event) => setTxCount(Number(event.target.value))} /></label><label><span>seed</span><input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} /></label><label><span>duration_ms</span><input type="number" min={1000} value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></label></div></article>
    {categories.map((category) => <PluginCategoryPanel key={category} category={category} catalog={catalog.filter((item) => item.category === category)} selection={selectionFor(category)} onChoose={choose} onConfig={updateConfig} />)}
    <article className="final-card wide"><div className="button-row"><button type="button" onClick={validate} disabled={busy}>Validate</button><button type="button" onClick={compile} disabled={busy}>Compile</button><button type="button" onClick={saveTemplate} disabled={busy}>Save method</button><button type="button" className="v3-secondary-button" onClick={run} disabled={busy || compatibility?.valid === false}>Run Real Cluster</button></div>{compatibility && <CompatibilityPanel result={compatibility} />}{compiled && <pre>{JSON.stringify(compiled, null, 2)}</pre>}{result && <pre>{JSON.stringify(result, null, 2)}</pre>}</article>
  </section>;
}

function defaultSelections(items: V5PluginManifest[]): V5PluginSelection[] { return Array.from(new Set(items.map((item) => item.category))).map((category) => { const plugin = items.find((item) => item.category === category)!; return { category, plugin_id: plugin.plugin_id, config: { ...plugin.default_config } }; }); }
function PluginCategoryPanel({ category, catalog, selection, onChoose, onConfig }: { category: string; catalog: V5PluginManifest[]; selection?: V5PluginSelection; onChoose: (category: string, plugin: V5PluginManifest) => void; onConfig: (category: string, key: string, value: unknown) => void }) { const selected = catalog.find((item) => item.plugin_id === selection?.plugin_id); return <article className="final-card wide"><h3>{categoryLabels[category] ?? category}</h3><div className="selectable-card-grid">{catalog.map((plugin) => <label key={plugin.plugin_id} className={`checkbox-card compact ${selection?.plugin_id === plugin.plugin_id ? "selected" : ""}`}><span><strong>{plugin.display_name}</strong><small>{plugin.plugin_id} / {plugin.implementation_status}</small><small>{plugin.supported_backends.join(", ")} / {plugin.truth_boundary}</small></span><input type="radio" checked={selection?.plugin_id === plugin.plugin_id} onChange={() => onChoose(category, plugin)} /></label>)}</div>{selected && <><p className="muted">{selected.description}</p><PluginConfigForm category={category} schema={selected.config_schema.properties ?? {}} value={selection?.config ?? {}} onChange={onConfig} /><p className="muted">requirements: {selected.requirements.join(", ") || "none"}; conflicts: {selected.conflicts.join(", ") || "none"}</p></>}</article> }
function PluginConfigForm({ category, schema, value, onChange }: { category: string; schema: Record<string, V5SchemaField>; value: Record<string, unknown>; onChange: (category: string, key: string, value: unknown) => void }) { return <div className="experiment-condition-grid">{Object.entries(schema).map(([key, field]) => <label key={key}><span>{field.title ?? key}</span><SchemaInput field={field} value={value[key] ?? field.default} onChange={(next) => onChange(category, key, next)} /><small>{field.description ?? ""}</small></label>)}</div> }
function SchemaInput({ field, value, onChange }: { field: V5SchemaField; value: unknown; onChange: (value: unknown) => void }) { if (field.enum) return <select value={String(value ?? "")} onChange={(event) => onChange(event.target.value)}>{field.enum.map((item) => <option key={item} value={item}>{item}</option>)}</select>; if (field.type === "boolean") return <input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} />; if (field.type === "integer" || field.type === "number") return <input type="number" min={field.minimum} max={field.maximum} value={Number(value ?? 0)} onChange={(event) => onChange(field.type === "integer" ? Number.parseInt(event.target.value, 10) : Number(event.target.value))} />; return <input value={String(value ?? "")} readOnly={field.readOnly} onChange={(event) => onChange(event.target.value)} /> }
function CompatibilityPanel({ result }: { result: V5CompatibilityResult }) { return <div><p className={result.valid ? "notice" : "file-error"}>{result.valid ? "compatible" : "blocked"}</p>{result.blockers.map((item) => <p className="file-error" key={item}>{item}</p>)}{result.warnings.map((item) => <p className="muted" key={item}>{item}</p>)}<pre>{JSON.stringify(result.resource_estimate, null, 2)}</pre></div> }
