import { expect, test } from "@playwright/test";

test("previews and runs a V5 real-cluster Formal RunGroup", async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto("/");
  await page.locator(".final-sidebar").getByRole("button", { name: "② 运行实验", exact: true }).click();
  await expect(page.getByTestId("v5-formal-run-page")).toBeVisible();
  await page.getByTestId("v5-run-method-v5_catalog_default").getByRole("checkbox").check();
  await expect(page.getByRole("button", { name: "预览正式实验矩阵" })).toBeEnabled();
  await page.getByLabel("nodes").fill("4");
  await page.getByLabel("shards").fill("1");
  await page.getByLabel("validators per shard").fill("4");
  await page.getByLabel("tx_count").fill("20");
  await page.getByLabel("cross_shard_ratio").fill("0");
  await page.getByLabel("seeds").fill("11");
  await page.getByLabel("repeats").fill("1");
  await page.getByRole("button", { name: "预览正式实验矩阵" }).click();
  await expect(page.getByTestId("v5-formal-preview-summary")).toContainText("矩阵行数：1");
  await expect(page.getByText("可运行", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "启动真实集群实验组" })).toBeEnabled();
  await page.getByLabel("tx_count").fill("21");
  await expect(page.getByRole("button", { name: "启动真实集群实验组" })).toBeDisabled();
  await page.getByRole("button", { name: "预览正式实验矩阵" }).click();
  await expect(page.getByTestId("v5-formal-preview-summary")).toContainText("矩阵行数：1");
  await expect(page.getByRole("button", { name: "启动真实集群实验组" })).toBeEnabled();
  await page.getByLabel("tx_count").fill("20");
  await expect(page.getByRole("button", { name: "启动真实集群实验组" })).toBeDisabled();
  await page.getByRole("button", { name: "预览正式实验矩阵" }).click();
  await expect(page.getByRole("button", { name: "启动真实集群实验组" })).toBeEnabled();
  await page.getByRole("button", { name: "启动真实集群实验组" }).click();
  await expect(page.getByText("run_group_id：", { exact: false })).toBeVisible();
  await expect.poll(async () => page.getByTestId("v5-formal-group-summary").innerText(), { timeout: 180_000 }).toContain("状态：已完成");
  const child = page.getByTestId("v5-formal-child-table").locator("tbody tr").first().locator("td");
  await expect(child.nth(7)).toHaveText("completed");
  await expect(child.nth(8)).toHaveText("20");
  await expect(child.nth(9)).toHaveText("0");
  await expect(child.nth(10)).toHaveText("0");
  await expect(child.nth(11)).toHaveText("true");
});
