import { expect, test } from "@playwright/test";
import { selectOnlySuite } from "./v5-formal-test-helpers";

test("fault matrix only exposes runtime-supported modes and blocks cross-shard packet loss", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("primary-navigation").getByRole("button", { name: "② 运行实验" }).click();
  await page.getByTestId("v5-run-method-v5_catalog_default").getByRole("checkbox").check();
  await selectOnlySuite(page, "fault_recovery_experiment");
  await page.getByLabel("tx_count").fill("20");
  const editor = page.getByTestId("v5-point-editor-故障扫描点");
  await editor.getByRole("button", { name: "添加扫描点" }).click();
  await editor.getByRole("button", { name: "添加扫描点" }).click();
  const modes = editor.locator("select");
  await modes.nth(0).selectOption("disabled");
  await modes.nth(1).selectOption("network_drop");
  await expect(editor).not.toContainText("kill_node");
  await expect(editor).not.toContainText("restart_node");
  await expect(editor).not.toContainText("drop_every");
  await expect(editor.getByLabel("drop_rate")).toBeVisible();
  await editor.getByLabel("drop_rate").fill("0.1");
  const allowed = page.waitForResponse((response) => response.url().includes("/api/v5/formal/preview") && response.request().method() === "POST");
  await page.getByTestId("v5-formal-preview-button").click();
  const allowedBody = await (await allowed).json();
  expect(allowedBody.rows).toHaveLength(2);
  expect(allowedBody.rows.map((row: { fault_point: { mode: string } }) => row.fault_point.mode).sort()).toEqual(["disabled", "network_drop"]);
  expect(allowedBody.rows.every((row: { runnable: boolean; blockers: unknown[]; execution_backend: string }) => row.runnable && row.blockers.length === 0 && row.execution_backend === "real_cluster")).toBe(true);

  await page.getByLabel("nodes").fill("8");
  await page.getByLabel("shards").fill("2");
  await page.getByLabel("validators per shard").fill("4");
  await page.getByLabel("cross_shard_ratio").fill("0.25");
  let createCount = 0;
  page.on("request", (request) => { if (request.url().includes("/api/v5/formal/run-groups") && request.method() === "POST") createCount += 1; });
  const blocked = page.waitForResponse((response) => response.url().includes("/api/v5/formal/preview") && response.request().method() === "POST");
  await page.getByTestId("v5-formal-preview-button").click();
  const blockedBody = await (await blocked).json();
  expect(blockedBody.rows.some((row: { runnable: boolean; blockers: string[] }) => !row.runnable && row.blockers.some((blocker) => blocker.includes("retransmission")))).toBe(true);
  await expect(page.getByTestId("v5-formal-run-page")).toContainText("可靠重传");
  await expect(page.getByTestId("v5-start-run-group-button")).toBeDisabled();
  expect(createCount).toBe(0);
});
