import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";

import { createV5FormalRunGroup, fetchV5FormalRunGroup, fetchV5PluginCatalog, listV3SavedConfigs, previewV5FormalRun, validateV5ExperimentSpec, type V5CompatibilityResult, type V5ExperimentSpec, type V5FormalMethod, type V5FormalPreviewResponse, type V5FormalRunRequest, type V5FormalRunGroupDetail, type V5FormalSuite, type V5PluginManifest, type V5PluginSelection } from "../api";
import { backendLabel, blockerLabel, categoryLabel, faultModeLabel, roleLabel, statusLabel, suiteLabel } from "../v5Labels";
import { applyV5MethodSelections, defaultV5PluginSelections, parseSavedV5Method } from "../v5MethodProfile";

const recentGroupKey = "mbe.v5FormalRunGroupId";
const suites: V5FormalSuite[] = ["main_experiment", "comparison_experiment", "ablation_experiment", "workload_sensitivity", "topology_scaling", "fault_recovery_experiment"];
type Topology = { nodes: number; shards: number; validators_per_shard: number };
type WorkloadPoint = { tx_count: number; cross_shard_ratio: number; timeout_every: number };
type FaultMode = "disabled" | "delay_only" | "network_drop";
type FaultPoint = { mode: FaultMode; delay_ms?: number; drop_rate?: number; drop_message_types?: string[] };
type Props = { onOpenResults?: (groupId: string) => void; onPreferredMethodUnavailable?: (methodId: string) => void; preferredMethodId?: string };

export default function V5FormalRunPage({ onOpenResults, onPreferredMethodUnavailable, preferredMethodId = "" }: Props) {
  const [catalog, setCatalog] = useState<V5PluginManifest[]>([]);
  const [savedMethods, setSavedMethods] = useState<V5FormalMethod[]>([]);
  const [selectedMethods, setSelectedMethods] = useState<string[]>([]);
  const [selectedSuites, setSelectedSuites] = useState<V5FormalSuite[]>(["main_experiment"]);
  const [topology, setTopology] = useState<Topology>({ nodes: 4, shards: 1, validators_per_shard: 4 });
  const [txCount, setTxCount] = useState(20); const [crossShardRatio, setCrossShardRatio] = useState(0);
  const [timeoutEvery, setTimeoutEvery] = useState(0); const [timeoutEnabled, setTimeoutEnabled] = useState(false);
  const [seedText, setSeedText] = useState("11"); const [repeats, setRepeats] = useState(1);
  const [workloadPoints, setWorkloadPoints] = useState<WorkloadPoint[]>([]);
  const [topologyPoints, setTopologyPoints] = useState<Topology[]>([]);
  const [faultPoints, setFaultPoints] = useState<FaultPoint[]>([]);
  const [preview, setPreview] = useState<V5FormalPreviewResponse | null>(null);
  const [previewRequest, setPreviewRequest] = useState<V5FormalRunRequest | null>(null);
  const [methodCompatibility, setMethodCompatibility] = useState<Record<string, V5CompatibilityResult>>({});
  const [groupDetail, setGroupDetail] = useState<V5FormalRunGroupDetail | null>(null); const [groupId, setGroupId] = useState("");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [catalogError, setCatalogError] = useState(""); const [savedError, setSavedError] = useState(""); const [busy, setBusy] = useState(false);
  const pollTimer = useRef<number | null>(null); const formRevision = useRef(0); const preferredConsumed = useRef(false); const lastKnownNonterminal = useRef(false);
  const catalogDefault = useMemo<V5FormalMethod>(() => ({ method_id: "v5_catalog_default", display_name: "目录默认基线", plugin_overrides: {}, role: "baseline" }), []);
  const methods = useMemo(() => [catalogDefault, ...savedMethods], [catalogDefault, savedMethods]);
  const seeds = useMemo(() => parseSeeds(seedText), [seedText]);
  const catalogReady = useMemo(() => defaultV5PluginSelections(catalog).length === 17, [catalog]);
  const previewRunnable = Boolean(preview?.rows.length && preview.rows.every((row) => row.runnable && !row.blockers.length));
  const selected = methods.filter((method) => selectedMethods.includes(method.method_id));
  const resources = estimateFormalResources(selectedSuites, selected.length, seeds.length, repeats, topology, txCount, workloadPoints, topologyPoints, faultPoints);
  const estimatedChildren = resources.children;

  useEffect(() => { void loadCatalog(); const stored = window.localStorage.getItem(recentGroupKey); if (stored) void queryGroup(stored, true); return stopPolling; }, []);
  useEffect(() => { if (groupId && groupDetail && !terminal(groupDetail.group.status)) schedulePolling(groupId); else stopPolling(); return stopPolling; }, [groupId, groupDetail?.group.status]);

  async function loadCatalog() {
    const [catalogResult, savedResult] = await Promise.allSettled([fetchV5PluginCatalog("real_cluster"), listV3SavedConfigs("method")]);
    if (catalogResult.status === "fulfilled") { setCatalog(catalogResult.value); setCatalogError(""); }
    else { setCatalogError(errorMessage(catalogResult.reason)); return; }
    if (savedResult.status === "fulfilled") {
      const parsed = savedResult.value.map((item) => parseSavedV5Method(item, catalogResult.value)).filter((item): item is V5FormalMethod => item !== null);
      setSavedMethods(parsed); setSavedError("");
      if (!preferredConsumed.current && preferredMethodId) {
        preferredConsumed.current = true; const preferred = parsed.find((item) => item.method_id === preferredMethodId);
        if (preferred) { setSelectedMethods([preferred.method_id]); invalidatePreview(); setMessage(`来自实验设计：${preferred.display_name}`); }
        else { setSelectedMethods([]); onPreferredMethodUnavailable?.(preferredMethodId); setError(`实验设计传入的方法 ${preferredMethodId} 已不存在或不兼容，未自动选择目录默认基线。`); }
      }
    } else { setSavedMethods([]); setSavedError("已保存方法暂时无法读取；目录默认基线仍可使用。"); }
  }
  function invalidatePreview() { formRevision.current += 1; setPreview(null); setPreviewRequest(null); setMethodCompatibility({}); }
  function update<T>(fn: () => void) { fn(); invalidatePreview(); }
  function buildRequest(): V5FormalRunRequest | null {
    const problem = formError({ catalogReady, selected, selectedSuites, topology, txCount, crossShardRatio, timeoutEvery: timeoutEnabled || selectedSuites.includes("fault_recovery_experiment") ? timeoutEvery : 0, seeds, repeats, workloadPoints, topologyPoints, faultPoints, estimatedChildren });
    if (problem) { setError(problem); return null; }
    const pluginSelections: V5PluginSelection[] = defaultV5PluginSelections(catalog).map((item) => item.category === "workload" ? { ...item, config: { ...item.config, cross_shard_ratio: crossShardRatio, timeout_every: timeoutEnabled || selectedSuites.includes("fault_recovery_experiment") ? timeoutEvery : 0 } } : item);
    const base_spec: V5ExperimentSpec = { name: "v5_formal_real_cluster", execution_backend: "real_cluster", plugin_selections: pluginSelections, topology, tx_count: txCount, seed: seeds[0], duration_ms: 6000, fault_policy: { mode: "disabled" }, requested_metrics: [] };
    const e2e = new URLSearchParams(window.location.search).get("e2e") === "1";
    return { execution_backend: "real_cluster", plan: { name: "v5_formal_real_cluster", base_spec, suites: selectedSuites, methods: selected, seeds, repeats, workload_points: workloadPoints, topology_points: topologyPoints, fault_points: faultPoints, source_label: e2e ? "e2e" : "user", tags: e2e ? ["e2e"] : [] } };
  }
  async function previewMatrix() {
    const request = buildRequest(); if (!request) return; const revision = formRevision.current; setBusy(true);
    try {
      const entries = await Promise.all(request.plan.methods.map(async (method) => [method.method_id, await validateV5ExperimentSpec(applyV5MethodSelections(request.plan.base_spec, method))] as const));
      const compatibility = Object.fromEntries(entries); const response = await previewV5FormalRun(request); if (revision !== formRevision.current) return;
      const merged = { ...response, rows: response.rows.map((row) => { const result = compatibility[row.method_config_id]; return result ? { ...row, runnable: row.runnable && result.valid, blockers: [...new Set([...row.blockers, ...result.blockers])], warnings: [...new Set([...row.warnings, ...result.warnings])] } : row; }) };
      setMethodCompatibility(compatibility); setPreview(merged); setPreviewRequest(request); setMessage(`后端正式矩阵包含 ${merged.rows.length} 个真实集群子实验。`); setError("");
    } catch (caught) { if (revision === formRevision.current) setError(blockerLabel(errorMessage(caught))); } finally { setBusy(false); }
  }
  async function startGroup() { if (!previewRequest || !previewRunnable) { setError("请先预览当前配置，并确保所有矩阵行可运行。"); return; } setBusy(true); try { const group = await createV5FormalRunGroup(previewRequest); window.localStorage.setItem(recentGroupKey, group.run_group_id); setGroupId(group.run_group_id); setGroupDetail({ group, children: [] }); setMessage(`已启动真实集群实验组 ${group.run_group_id}。`); setError(""); await queryGroup(group.run_group_id, true); } catch (caught) { setError(errorMessage(caught)); } finally { setBusy(false); } }
  function schedulePolling(id: string) { stopPolling(); pollTimer.current = window.setTimeout(() => void queryGroup(id, true), 1500); }
  async function queryGroup(id = groupId, quiet = false) { if (!id) return; try { const detail = await fetchV5FormalRunGroup(id); setGroupId(id); setGroupDetail(detail); lastKnownNonterminal.current = !terminal(detail.group.status); if (!quiet) setMessage(`已刷新实验组 ${id}。`); setError(""); if (lastKnownNonterminal.current) schedulePolling(id); else stopPolling(); } catch (caught) { setError(errorMessage(caught)); if (lastKnownNonterminal.current) schedulePolling(id); } }
  function stopPolling() { if (pollTimer.current !== null) { window.clearTimeout(pollTimer.current); pollTimer.current = null; } }
  const showTimeout = timeoutEnabled || selectedSuites.includes("fault_recovery_experiment");
  return <section className="page-grid" data-testid="v5-formal-run-page">
    <article className="final-card wide page-hero"><p className="eyebrow">V5 正式实验 / real_cluster</p><h2>运行实验</h2><p>正式执行使用独立 OS 进程和 localhost TCP。当前数据源为确定性签名合成负载；真实集群失败会直接失败，不会回退到 Simulation 或 V4 smoke。</p>{catalogError && <p className="file-error">{catalogError}</p>}{savedError && <p className="notice">{savedError}</p>}{error && <p className="file-error">{error}</p>}{message && <p className="notice">{message}</p>}<CurrentMethods methods={selected} preferredMethodId={preferredMethodId} /></article>
    <article className="final-card wide"><h3>实验类型</h3><div className="selectable-card-grid">{suites.map((suite) => <label key={suite} data-testid={`v5-suite-${suite}`} className={`checkbox-card compact ${selectedSuites.includes(suite) ? "selected" : ""}`}><span><strong>{suiteLabel(suite)}</strong><small>{suite}</small></span><input type="checkbox" checked={selectedSuites.includes(suite)} onChange={() => update(() => setSelectedSuites((current) => toggle(suite, current)))} /></label>)}</div></article>
    <article className="final-card wide"><h3>实验方法</h3><p className="muted">正式矩阵当前只支持方法级插件 ID 覆盖；插件参数由基础 ExperimentSpec 统一提供。</p><div className="selectable-card-grid">{methods.map((method) => <label key={method.method_id} data-testid={`v5-run-method-${method.method_id}`} className={`checkbox-card compact ${selectedMethods.includes(method.method_id) ? "selected" : ""}`}><span><strong>{method.display_name}</strong><small>方法 ID：{method.method_id}</small><small>角色：{roleLabel(method.role ?? "custom")}</small></span><input type="checkbox" checked={selectedMethods.includes(method.method_id)} onChange={() => update(() => setSelectedMethods((current) => toggle(method.method_id, current)))} /></label>)}</div>{!selected.length && <p className="file-error">尚未选择执行方法，请选择已保存方法或主动选择目录默认基线。</p>}</article>
    <article className="final-card wide"><h3>负载与拓扑</h3><p className="muted">数据来源：确定性签名合成负载</p><div className="experiment-condition-grid"><Number label="节点数" aria="nodes" value={topology.nodes} onChange={(value) => update(() => setTopology({ ...topology, nodes: value }))} /><Number label="分片数" aria="shards" value={topology.shards} onChange={(value) => update(() => setTopology({ ...topology, shards: value }))} /><Number label="每片验证节点数" aria="validators per shard" value={topology.validators_per_shard} onChange={(value) => update(() => setTopology({ ...topology, validators_per_shard: value }))} /><Number label="交易数量" aria="tx_count" value={txCount} onChange={(value) => update(() => setTxCount(value))} /><Number label="跨片交易比例" aria="cross_shard_ratio" value={crossShardRatio} step={0.01} onChange={(value) => update(() => setCrossShardRatio(value))} />{showTimeout && <Number label="每隔多少笔跨片交易触发一次超时" aria="timeout_every" value={timeoutEvery} onChange={(value) => update(() => setTimeoutEvery(value))} />}<label><span>随机种子</span><input aria-label="seeds" value={seedText} onChange={(event) => update(() => setSeedText(event.target.value))} /><small>逗号分隔的整数，最多 10 个。</small></label><Number label="重复次数" aria="repeats" value={repeats} onChange={(value) => update(() => setRepeats(value))} /></div>{!selectedSuites.includes("fault_recovery_experiment") && <label><input type="checkbox" checked={timeoutEnabled} onChange={(event) => update(() => setTimeoutEnabled(event.target.checked))} /> 启用超时/退款工况</label>}</article>
    {selectedSuites.includes("workload_sensitivity") && <PointEditor title="负载扫描点" onAdd={() => update(() => setWorkloadPoints((items) => [...items, { tx_count: txCount, cross_shard_ratio: crossShardRatio, timeout_every: 0 }]))}>{workloadPoints.map((point, index) => <div key={index} className="experiment-condition-grid"><Number label="交易数量" value={point.tx_count} onChange={(value) => update(() => setWorkloadPoints(replace(workloadPoints, index, { ...point, tx_count: value })))} /><Number label="跨片交易比例" value={point.cross_shard_ratio} step={0.01} onChange={(value) => update(() => setWorkloadPoints(replace(workloadPoints, index, { ...point, cross_shard_ratio: value })))} /><Number label="timeout_every" value={point.timeout_every} onChange={(value) => update(() => setWorkloadPoints(replace(workloadPoints, index, { ...point, timeout_every: value })))} /><button type="button" onClick={() => update(() => setWorkloadPoints(workloadPoints.filter((_, item) => item !== index)))}>删除点</button></div>)}</PointEditor>}
    {selectedSuites.includes("topology_scaling") && <PointEditor title="拓扑扫描点" onAdd={() => update(() => setTopologyPoints((items) => [...items, { ...topology }]))}>{topologyPoints.map((point, index) => <div key={index} className="experiment-condition-grid"><Number label="节点数" value={point.nodes} onChange={(value) => update(() => setTopologyPoints(replace(topologyPoints, index, { ...point, nodes: value })))} /><Number label="分片数" value={point.shards} onChange={(value) => update(() => setTopologyPoints(replace(topologyPoints, index, { ...point, shards: value })))} /><Number label="每片验证节点数" value={point.validators_per_shard} onChange={(value) => update(() => setTopologyPoints(replace(topologyPoints, index, { ...point, validators_per_shard: value })))} /><button type="button" onClick={() => update(() => setTopologyPoints(topologyPoints.filter((_, item) => item !== index)))}>删除点</button></div>)}</PointEditor>}
    {selectedSuites.includes("fault_recovery_experiment") && <PointEditor title="故障扫描点" onAdd={() => update(() => setFaultPoints((items) => [...items, { mode: "disabled" }]))}>
      {faultPoints.map((point, index) => <div key={index} className="experiment-condition-grid">
        <label><span>故障模式</span><select value={point.mode} onChange={(event) => update(() => setFaultPoints(replace(faultPoints, index, defaultFaultPoint(event.target.value as FaultMode))))}>{(["disabled", "delay_only", "network_drop"] as FaultMode[]).map((mode) => <option key={mode} value={mode}>{faultModeLabel(mode)}（{mode}）</option>)}</select></label>
        {point.mode === "delay_only" && <Number label="delay_ms" value={point.delay_ms ?? 5} min={0} max={1000} onChange={(value) => update(() => setFaultPoints(replace(faultPoints, index, { ...point, delay_ms: value })))} />}
        {point.mode === "network_drop" && <><Number label="drop_rate" value={point.drop_rate ?? 0.1} min={0.01} max={1} step={0.01} onChange={(value) => update(() => setFaultPoints(replace(faultPoints, index, { ...point, drop_rate: value })))} /><Number label="delay_ms" value={point.delay_ms ?? 0} min={0} max={1000} onChange={(value) => update(() => setFaultPoints(replace(faultPoints, index, { ...point, delay_ms: value })))} /></>}
        <button type="button" onClick={() => update(() => setFaultPoints(faultPoints.filter((_, item) => item !== index)))}>删除点</button>
      </div>)}
    </PointEditor>}
    <article className="final-card wide"><p>预计子实验：<strong data-testid="v5-estimated-children">{resources.children}</strong>；预计节点进程启动次数：<strong data-testid="v5-estimated-process-starts">{resources.processStarts}</strong>；预计交易总量：<strong data-testid="v5-estimated-transactions">{resources.transactions}</strong>{estimatedChildren > 20 && "。超过 20 个子实验，建议分批执行。"}{estimatedChildren > 100 && <span className="file-error">。超过后端 100 个子实验硬上限。</span>}</p><div className="button-row"><button type="button" onClick={() => void previewMatrix()} disabled={busy || !catalogReady || !selected.length}>预览正式实验矩阵</button><button type="button" className="v3-secondary-button" onClick={() => void startGroup()} disabled={busy || !previewRunnable}>启动真实集群实验组</button></div>{Object.entries(methodCompatibility).map(([id, result]) => <p key={id} className={result.valid ? "muted" : "file-error"}>方法 {id}：{result.valid ? "兼容" : result.blockers.map(blockerLabel).join("；")}</p>)}{preview && <PreviewTable preview={preview} />}</article>
    <article className="final-card wide"><div className="section-heading"><div><h3>实验组状态</h3><p className="muted">最近的实验组 ID 保存于浏览器，仅用于刷新后的查询，不会自动重新执行。</p></div><button type="button" onClick={() => void queryGroup()} disabled={!groupId || busy}>重新查询</button></div>{groupId && <p><strong>run_group_id：</strong><code>{groupId}</code> {onOpenResults && <button type="button" onClick={() => onOpenResults(groupId)}>查看结果与产物</button>}</p>}{groupDetail && <GroupStatus detail={groupDetail} />}</article>
  </section>;
}

function CurrentMethods({ methods, preferredMethodId }: { methods: V5FormalMethod[]; preferredMethodId: string }) { return <div data-testid="v5-run-preferred-method"><strong>当前执行方法：</strong>{methods.length ? methods.map((method) => <span key={method.method_id}> {method.display_name}（{method.method_id}，{method.method_id === preferredMethodId ? "来源：实验设计" : method.method_id === "v5_catalog_default" ? "来源：目录默认基线" : "来源：已保存方法"}，{roleLabel(method.role ?? "custom")}）</span>) : "未选择"}</div>; }
function NumberInput({ label, aria, value, onChange, step = 1, min = 0, max }: { label: string; aria?: string; value: number; onChange: (value: number) => void; step?: number; min?: number; max?: number }) { return <label><span>{label}</span><input aria-label={aria ?? label} type="number" min={min} max={max} step={step} value={value} onChange={(event) => onChange(globalThis.Number(event.target.value))} /></label>; }
const Number = NumberInput;
function PointEditor({ title, onAdd, children }: { title: string; onAdd: () => void; children: ReactNode }) { return <article className="final-card wide" data-testid={`v5-point-editor-${title}`}><div className="section-heading"><h3>{title}</h3><button type="button" onClick={onAdd}>添加扫描点</button></div>{children}</article>; }
function PreviewTable({ preview }: { preview: V5FormalPreviewResponse }) { return <div className="table-wrap"><p data-testid="v5-formal-preview-summary"><strong>执行后端：</strong>{preview.execution_backend}；<strong>矩阵行数：</strong>{preview.rows.length}</p><table><thead><tr><th>实验类型</th><th>方法</th><th>方法配置 ID</th><th>种子</th><th>重复</th><th>拓扑</th><th>交易数量</th><th>后端</th><th>兼容性</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.child_run_id} data-method-config-id={row.method_config_id}><td>{suiteLabel(row.suite_type)}</td><td>{row.method.display_name}</td><td>{row.method_config_id}</td><td>{row.seed}</td><td>{row.repeat_index + 1}</td><td>{row.topology_point.nodes}/{row.topology_point.shards}/{row.topology_point.validators_per_shard}</td><td>{row.estimated_transactions}</td><td>{row.execution_backend}</td><td>{row.runnable ? "可运行" : row.blockers.map(blockerLabel).join("；") || "已阻止"}</td></tr>)}</tbody></table></div>; }
function GroupStatus({ detail }: { detail: V5FormalRunGroupDetail }) { const failed = detail.children.filter((child) => ["failed", "blocked"].includes(child.status)).length; return <><p data-testid="v5-formal-group-summary"><strong>状态：</strong>{statusLabel(detail.group.status)}；<strong>执行后端：</strong>{backendLabel(detail.group.execution_backend)}；<strong>子实验：</strong>{detail.group.completed_child_runs}/{detail.group.total_child_runs}；<strong>失败：</strong>{failed}</p><div className="table-wrap"><table data-testid="v5-formal-child-table"><thead><tr><th>子实验</th><th>实验类型</th><th>方法</th><th>种子</th><th>重复</th><th>拓扑</th><th>交易</th><th>状态</th><th>终态</th><th>未完成</th><th>孤儿进程</th><th>无回退</th></tr></thead><tbody>{detail.children.map((child) => { const finality = child.result?.summary?.finality_evidence; return <tr key={child.child_run_id}><td>{child.child_run_id}</td><td>{suiteLabel(child.suite_type)}</td><td>{child.method.display_name}</td><td>{child.seed}</td><td>{child.repeat_index + 1}</td><td>{child.topology_point.nodes}/{child.topology_point.shards}/{child.topology_point.validators_per_shard}</td><td>{child.estimated_transactions}</td><td>{child.status}</td><td>{finality?.terminal_unique_tx_count ?? "—"}</td><td>{finality?.incomplete_unique_tx_count ?? "—"}</td><td>{child.result?.summary?.orphan_process_count ?? "—"}</td><td>{child.result?.summary?.no_fallback === undefined ? "—" : String(child.result.summary.no_fallback)}</td></tr>; })}</tbody></table></div></>; }
function formError(input: { catalogReady: boolean; selected: V5FormalMethod[]; selectedSuites: V5FormalSuite[]; topology: Topology; txCount: number; crossShardRatio: number; timeoutEvery: number; seeds: number[]; repeats: number; workloadPoints: WorkloadPoint[]; topologyPoints: Topology[]; faultPoints: FaultPoint[]; estimatedChildren: number }): string | null {
  if (!input.catalogReady) return "真实集群插件目录不完整，无法预览。"; if (!input.selected.length) return "请至少选择一个执行方法。"; if (!input.selectedSuites.length) return "请至少选择一种实验类型。"; if (!input.seeds.length) return "随机种子必须是一到十个不重复整数。"; if (input.topology.nodes < 1 || input.topology.shards < 1 || input.topology.validators_per_shard < 1 || input.topology.nodes !== input.topology.shards * input.topology.validators_per_shard) return "节点数必须等于分片数乘以每片验证节点数。"; if (input.txCount < 1 || !globalThis.Number.isInteger(input.txCount)) return "交易数量必须为正整数。"; if (input.crossShardRatio < 0 || input.crossShardRatio > 1) return "跨片交易比例必须在 0 到 1 之间。"; if (input.selectedSuites.includes("comparison_experiment") && input.selected.length < 2) return "方法对比实验至少需要两个方法。"; if (input.selectedSuites.includes("ablation_experiment") && (!input.selected.some((item) => item.role === "main") || !input.selected.some((item) => item.role === "ablation" || item.role === "baseline"))) return "消融实验需要一个完整方法和至少一个消融或基线方法。"; if (input.selectedSuites.includes("workload_sensitivity") && input.workloadPoints.length < 2) return "负载敏感性实验至少需要两个负载扫描点。"; if (input.selectedSuites.includes("topology_scaling") && input.topologyPoints.length < 2) return "拓扑扩展性实验至少需要两个拓扑扫描点。"; if (input.selectedSuites.includes("fault_recovery_experiment")) { if (input.faultPoints.length < 2 || !input.faultPoints.some((item) => item.mode === "disabled") || !input.faultPoints.some((item) => item.mode !== "disabled")) return "故障与恢复实验至少需要两个点，必须包含无故障基准点和一个故障点。"; for (const point of input.faultPoints) { if (point.mode === "delay_only" && (!globalThis.Number.isInteger(point.delay_ms) || point.delay_ms! < 0 || point.delay_ms! > 1000)) return "网络延迟需要 0 到 1000 的整数 delay_ms。"; if (point.mode === "network_drop" && (!(point.drop_rate! > 0 && point.drop_rate! <= 1) || (point.delay_ms !== undefined && (!globalThis.Number.isInteger(point.delay_ms) || point.delay_ms < 0 || point.delay_ms > 1000)))) return "随机丢包需要 0 到 1 之间的 drop_rate，delay_ms 需要为 0 到 1000 的整数。"; } } if (input.estimatedChildren > 100) return "正式矩阵超过 100 个子实验硬上限。"; return null;
}
function defaultFaultPoint(mode: FaultMode): FaultPoint { if (mode === "delay_only") return { mode, delay_ms: 5 }; if (mode === "network_drop") return { mode, drop_rate: 0.1, delay_ms: 0 }; return { mode: "disabled" }; }
function estimateFormalResources(selectedSuites: V5FormalSuite[], methods: number, seeds: number, repeats: number, topology: Topology, txCount: number, workloadPoints: WorkloadPoint[], topologyPoints: Topology[], faultPoints: FaultPoint[]): { children: number; processStarts: number; transactions: number } { const factor = methods * seeds * repeats; return selectedSuites.reduce((total, suite) => { const points = suite === "workload_sensitivity" ? workloadPoints.map((point) => ({ nodes: topology.nodes, txCount: point.tx_count })) : suite === "topology_scaling" ? topologyPoints.map((point) => ({ nodes: point.nodes, txCount })) : suite === "fault_recovery_experiment" ? faultPoints.map(() => ({ nodes: topology.nodes, txCount })) : [{ nodes: topology.nodes, txCount }]; return { children: total.children + points.length * factor, processStarts: total.processStarts + points.reduce((sum, point) => sum + point.nodes * factor, 0), transactions: total.transactions + points.reduce((sum, point) => sum + point.txCount * factor, 0) }; }, { children: 0, processStarts: 0, transactions: 0 }); }
function parseSeeds(value: string): number[] { const values = value.split(",").map((item) => item.trim()).filter(Boolean).map(globalThis.Number); return !values.length || values.length > 10 || values.some((item) => !globalThis.Number.isInteger(item)) ? [] : [...new Set(values)]; }
function toggle<T>(item: T, values: T[]): T[] { return values.includes(item) ? values.filter((value) => value !== item) : [...values, item]; }
function replace<T>(items: T[], index: number, value: T): T[] { return items.map((item, current) => current === index ? value : item); }
function terminal(status: string): boolean { return ["completed", "completed_with_failures", "failed", "cancelled"].includes(status); }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
