import { useEffect, useMemo, useRef, useState } from "react";

import { createV3SavedConfig, fetchV5PluginCatalog, listV3SavedConfigs, validateV5ExperimentSpec, type V3SavedConfig, type V5CompatibilityResult, type V5PluginManifest, type V5PluginSelection } from "../api";
import { V5_METHOD_PROFILE_SCHEMA_VERSION, buildV5MethodValidationSpec, parseSavedV5Method, v5MethodSelectionsFromCatalog } from "../v5MethodProfile";

type Props = { onOpenRun: (configId: string) => void; onDirtyChange?: (dirty: boolean) => void; saveRequestToken?: number };
const roles = ["main", "baseline", "ablation", "custom"];

export default function V5MethodDesignPage({ onOpenRun, onDirtyChange, saveRequestToken = 0 }: Props) {
  const [catalog, setCatalog] = useState<V5PluginManifest[]>([]);
  const [selections, setSelections] = useState<V5PluginSelection[]>([]);
  const [saved, setSaved] = useState<V3SavedConfig[]>([]);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [role, setRole] = useState("main");
  const [compatibility, setCompatibility] = useState<V5CompatibilityResult | null>(null);
  const [savedConfigId, setSavedConfigId] = useState("");
  const [validatedSnapshot, setValidatedSnapshot] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const revision = useRef(0);
  const initialSnapshot = useRef("");
  const snapshot = useMemo(() => JSON.stringify(selections.map((item) => [item.category, item.plugin_id]).sort()), [selections]);
  const validCurrent = Boolean(name.trim() && compatibility?.valid && validatedSnapshot === snapshot);
  const designSnapshot = useMemo(() => JSON.stringify({ name, description, role, selections: selections.map((item) => [item.category, item.plugin_id]) }), [name, description, role, selections]);

  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!initialSnapshot.current && selections.length) initialSnapshot.current = designSnapshot; onDirtyChange?.(Boolean(initialSnapshot.current && initialSnapshot.current !== designSnapshot)); }, [designSnapshot, onDirtyChange, selections.length]);
  useEffect(() => { if (saveRequestToken > 0) void save(true); }, [saveRequestToken]);
  async function load() { const [catalogResult, savedResult] = await Promise.allSettled([fetchV5PluginCatalog("real_cluster"), listV3SavedConfigs("method")]); if (catalogResult.status === "fulfilled") { setCatalog(catalogResult.value); setSelections(v5MethodSelectionsFromCatalog(catalogResult.value)); } else { setError(text(catalogResult.reason)); } if (savedResult.status === "fulfilled") setSaved(savedResult.value); else setMessage("已保存方法暂时无法读取；仍可设计新的目录方法。"); }
  function change(category: string, pluginId: string) { const plugin = catalog.find((item) => item.category === category && item.plugin_id === pluginId); if (!plugin) { setError(`Plugin ${pluginId} is not available for ${category}.`); return; } revision.current += 1; setSelections((current) => current.map((item) => item.category === category ? { ...item, plugin_id: pluginId, config: { ...plugin.default_config } } : item)); setCompatibility(null); setValidatedSnapshot(""); setMessage(""); setError(""); }
  async function validate() { const current = snapshot; const requestRevision = revision.current; setBusy(true); try { const result = await validateV5ExperimentSpec(buildV5MethodValidationSpec(catalog, selections)); if (requestRevision !== revision.current || current !== snapshot) return; setCompatibility(result); setValidatedSnapshot(current); setError(""); } catch (caught) { if (requestRevision === revision.current) setError(text(caught)); } finally { setBusy(false); } }
  async function save(continueToRun: boolean) { if (!validCurrent) { setError("请先完成方法名称并验证当前插件组合。"); return; } setBusy(true); try { const profile = await createV3SavedConfig({ config_kind: "method", name: name.trim(), description, owner_label: "local_user", tags: ["v5", "real_cluster", role], validation_status: "runnable", last_validation: compatibility ?? undefined, payload: { schema_version: V5_METHOD_PROFILE_SCHEMA_VERSION, plugin_selections: selections, plugin_parameters: selections, compatibility_snapshot: compatibility, source_composer_draft: { source: "v5_method_designer", role } } }); setSaved((current) => [profile, ...current]); setSavedConfigId(profile.config_id); initialSnapshot.current = designSnapshot; onDirtyChange?.(false); setMessage(`已保存 ${profile.config_id}。`); setError(""); if (continueToRun) onOpenRun(profile.config_id); } catch (caught) { setError(text(caught)); } finally { setBusy(false); } }
  const methods = saved.map((item) => ({ saved: item, method: parseSavedV5Method(item, catalog) })).filter((item): item is { saved: V3SavedConfig; method: NonNullable<ReturnType<typeof parseSavedV5Method>> } => item.method !== null);
  return <section className="page-grid" data-testid="v5-method-design-page">
    <article className="final-card wide page-hero"><p className="eyebrow">V5 插件化方法模板</p><h2>实验设计</h2><p>此页只设计方法与插件组合。负载、拓扑、交易数量、种子和重复次数在运行实验页设置。方法 Profile 复用 V3SavedConfig；当前 Formal Matrix 尚不支持方法独立插件参数。</p>{error && <p className="file-error">{error}</p>}{message && <p className="notice">{message}</p>}</article>
    <article className="final-card wide"><h3>方法基本信息</h3><div className="form-grid"><label><span>方法名称</span><input data-testid="v5-method-name" value={name} onChange={(event) => setName(event.target.value)} /></label><label><span>方法说明</span><input data-testid="v5-method-description" value={description} onChange={(event) => setDescription(event.target.value)} /></label><label><span>方法角色</span><select data-testid="v5-method-role" value={role} onChange={(event) => setRole(event.target.value)}>{roles.map((item) => <option key={item} value={item}>{({ main: "完整方法", baseline: "基线方法", ablation: "消融方法", custom: "自定义方法" }[item])}</option>)}</select></label></div></article>
    <article className="final-card wide"><h3>方法插件</h3><p className="muted">目录默认参数为只读展示。负载与故障注入属于实验工况，不属于方法变量。</p><div className="selectable-card-grid">{selections.map((selection) => <PluginSelector key={selection.category} selection={selection} catalog={catalog} onChange={change} />)}</div></article>
    <article className="final-card wide"><div className="button-row"><button data-testid="v5-method-validate" type="button" onClick={() => void validate()} disabled={busy || !catalog.length}>验证方法兼容性</button><button data-testid="v5-method-save" type="button" onClick={() => void save(false)} disabled={busy || !validCurrent}>保存方法</button><button data-testid="v5-method-save-and-run" type="button" onClick={() => void save(true)} disabled={busy || !validCurrent}>保存并进入运行实验</button></div>{savedConfigId && <p data-testid="v5-saved-method-id">{savedConfigId}</p>}<div data-testid="v5-method-compatibility"><strong>{compatibility ? String(compatibility.valid) : "尚未验证"}</strong>{compatibility?.blockers.map((item) => <p className="file-error" key={item}>{item}</p>)}{compatibility?.warnings.map((item) => <p className="muted" key={item}>{item}</p>)}</div></article>
    <article className="final-card wide" data-testid="v5-saved-method-library"><h3>已保存的 V5 方法</h3>{methods.map(({ saved, method }) => <div key={saved.config_id} className="section-heading"><p><strong>{saved.name}</strong> <code>{saved.config_id}</code>；{saved.validation_status}；{saved.tags.join(", ")}；{Object.keys(method.plugin_overrides).length} 个插件覆盖</p><button type="button" onClick={() => onOpenRun(saved.config_id)}>用于运行实验</button></div>)}{!methods.length && <p className="muted">历史 V3 方法仍可在高级功能 → V3 Composer（历史兼容）中使用。</p>}</article>
  </section>;
}

function PluginSelector({ selection, catalog, onChange }: { selection: V5PluginSelection; catalog: V5PluginManifest[]; onChange: (category: string, pluginId: string) => void }) { const choices = catalog.filter((item) => item.category === selection.category); const current = choices.find((item) => item.plugin_id === selection.plugin_id); return <article className="final-card" data-testid={`v5-method-category-${selection.category}`}><h4>{selection.category}</h4><select value={selection.plugin_id} onChange={(event) => onChange(selection.category, event.target.value)}>{choices.map((item) => <option key={item.plugin_id} value={item.plugin_id}>{item.display_name_zh || item.display_name}</option>)}</select>{current && <div data-testid={`v5-method-plugin-${current.plugin_id}`}><strong>{current.display_name_zh || current.display_name}</strong><code>{current.plugin_id}</code><p>{current.description_zh || current.description}</p><small>依赖：{current.requirements.join(", ") || "无"}；冲突：{current.conflicts.join(", ") || "无"}</small><p>{current.truth_boundary}</p><pre>{JSON.stringify(current.default_config, null, 2)}</pre></div>}</article>; }
function text(value: unknown): string { return value instanceof Error ? value.message : String(value); }
