import { useEffect, useMemo, useRef, useState } from "react";

import { createV3SavedConfig, fetchV5PluginCatalog, listV3SavedConfigs, validateV5ExperimentSpec, type V3SavedConfig, type V5CompatibilityResult, type V5PluginManifest, type V5PluginSelection } from "../api";
import { V5_METHOD_PROFILE_SCHEMA_VERSION, buildV5MethodValidationSpec, parseSavedV5Method, v5MethodSelectionsFromCatalog } from "../v5MethodProfile";

type Props = { onOpenRun: (configId: string) => void };
const roles = ["main", "baseline", "ablation", "custom"];

export default function V5MethodDesignPage({ onOpenRun }: Props) {
  const [catalog, setCatalog] = useState<V5PluginManifest[]>([]);
  const [selections, setSelections] = useState<V5PluginSelection[]>([]);
  const [saved, setSaved] = useState<V3SavedConfig[]>([]);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [role, setRole] = useState("main");
  const [compatibility, setCompatibility] = useState<V5CompatibilityResult | null>(null);
  const [savedConfigId, setSavedConfigId] = useState("");
  const [validatedSnapshot, setValidatedSnapshot] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const revision = useRef(0);
  const snapshot = useMemo(() => JSON.stringify(selections.map((item) => [item.category, item.plugin_id]).sort()), [selections]);
  const validCurrent = Boolean(name.trim() && compatibility?.valid && validatedSnapshot === snapshot);

  useEffect(() => { void load(); }, []);
  async function load() { try { const [items, configs] = await Promise.all([fetchV5PluginCatalog("real_cluster"), listV3SavedConfigs("method")]); setCatalog(items); setSelections(v5MethodSelectionsFromCatalog(items)); setSaved(configs); } catch (caught) { setError(text(caught)); } }
  function change(category: string, pluginId: string) { const plugin = catalog.find((item) => item.category === category && item.plugin_id === pluginId); if (!plugin) { setError(`Plugin ${pluginId} is not available for ${category}.`); return; } revision.current += 1; setSelections((current) => current.map((item) => item.category === category ? { ...item, plugin_id: pluginId, config: { ...plugin.default_config } } : item)); setCompatibility(null); setValidatedSnapshot(""); setMessage(""); setError(""); }
  async function validate() { const current = snapshot; const requestRevision = revision.current; setBusy(true); try { const result = await validateV5ExperimentSpec(buildV5MethodValidationSpec(catalog, selections)); if (requestRevision !== revision.current || current !== snapshot) return; setCompatibility(result); setValidatedSnapshot(current); setError(""); } catch (caught) { if (requestRevision === revision.current) setError(text(caught)); } finally { setBusy(false); } }
  async function save(continueToRun: boolean) { if (!validCurrent) return; setBusy(true); try { const profile = await createV3SavedConfig({ config_kind: "method", name: name.trim(), description, owner_label: "local_user", tags: ["v5", "real_cluster", role], validation_status: "runnable", last_validation: compatibility ?? undefined, payload: { schema_version: V5_METHOD_PROFILE_SCHEMA_VERSION, plugin_selections: selections, plugin_parameters: selections, compatibility_snapshot: compatibility, source_composer_draft: { source: "v5_method_designer", role } } }); setSaved((current) => [profile, ...current]); setSavedConfigId(profile.config_id); setMessage(`Saved ${profile.config_id}.`); setError(""); if (continueToRun) onOpenRun(profile.config_id); } catch (caught) { setError(text(caught)); } finally { setBusy(false); } }
  const methods = saved.map((item) => ({ saved: item, method: parseSavedV5Method(item, catalog) })).filter((item): item is { saved: V3SavedConfig; method: NonNullable<ReturnType<typeof parseSavedV5Method>> } => item.method !== null);
  return <section className="page-grid" data-testid="v5-method-design-page">
    <article className="final-card wide page-hero"><p className="eyebrow">V5 Plugin-driven Method Template</p><h2>实验设计</h2><p>Design only the method plugin combination. Workload, topology, tx_count, seeds, and repeats remain in Run Experiment. Method profiles reuse V3SavedConfig; method-level plugin parameter overrides are not yet supported.</p>{error && <p className="file-error">{error}</p>}{message && <p className="notice">{message}</p>}</article>
    <article className="final-card wide"><h3>Method Basics</h3><div className="form-grid"><label><span>Name</span><input data-testid="v5-method-name" value={name} onChange={(event) => setName(event.target.value)} /></label><label><span>Description</span><input data-testid="v5-method-description" value={description} onChange={(event) => setDescription(event.target.value)} /></label><label><span>Role</span><select data-testid="v5-method-role" value={role} onChange={(event) => setRole(event.target.value)}>{roles.map((item) => <option key={item}>{item}</option>)}</select></label></div></article>
    <article className="final-card wide"><h3>Plugin Categories</h3><p className="muted">Catalog defaults are read-only. Workload and fault injection are excluded because they are experiment conditions.</p><div className="selectable-card-grid">{selections.map((selection) => <PluginSelector key={selection.category} selection={selection} catalog={catalog} onChange={change} />)}</div></article>
    <article className="final-card wide"><div className="button-row"><button data-testid="v5-method-validate" type="button" onClick={() => void validate()} disabled={busy || !catalog.length}>Validate Method</button><button data-testid="v5-method-save" type="button" onClick={() => void save(false)} disabled={busy || !validCurrent}>Save Method</button><button data-testid="v5-method-save-and-run" type="button" onClick={() => void save(true)} disabled={busy || !validCurrent}>Save and Continue to Run</button></div>{savedConfigId && <p data-testid="v5-saved-method-id">{savedConfigId}</p>}<div data-testid="v5-method-compatibility"><strong>{compatibility ? String(compatibility.valid) : "unvalidated"}</strong>{compatibility?.blockers.map((item) => <p className="file-error" key={item}>{item}</p>)}{compatibility?.warnings.map((item) => <p className="muted" key={item}>{item}</p>)}{compatibility && <pre>{JSON.stringify({ resolved_plugins: compatibility.resolved_plugins, resource_estimate: compatibility.resource_estimate }, null, 2)}</pre>}</div></article>
    <article className="final-card wide" data-testid="v5-saved-method-library"><h3>Saved V5 Methods</h3>{methods.map(({ saved, method }) => <div key={saved.config_id} className="section-heading"><p><strong>{saved.name}</strong> <code>{saved.config_id}</code> {saved.validation_status}; {saved.tags.join(", ")}; {Object.keys(method.plugin_overrides).length} overrides; {saved.created_at}</p><button type="button" onClick={() => onOpenRun(saved.config_id)}>Use in Run Experiment</button></div>)}{!methods.length && <p className="muted">Historical V3 methods remain available in Advanced → V3 Composer.</p>}</article>
  </section>;
}

function PluginSelector({ selection, catalog, onChange }: { selection: V5PluginSelection; catalog: V5PluginManifest[]; onChange: (category: string, pluginId: string) => void }) { const choices = catalog.filter((item) => item.category === selection.category); const current = choices.find((item) => item.plugin_id === selection.plugin_id); return <article className="final-card" data-testid={`v5-method-category-${selection.category}`}><h4>{selection.category}</h4><select value={selection.plugin_id} onChange={(event) => onChange(selection.category, event.target.value)}>{choices.map((item) => <option key={item.plugin_id} value={item.plugin_id}>{item.display_name}</option>)}</select>{current && <div data-testid={`v5-method-plugin-${current.plugin_id}`}><code>{current.plugin_id}</code><p>{current.description}</p><small>requirements: {current.requirements.join(", ") || "none"}; conflicts: {current.conflicts.join(", ") || "none"}</small><p>{current.truth_boundary}</p><pre>{JSON.stringify(current.default_config, null, 2)}</pre></div>}</article>; }
function text(value: unknown): string { return value instanceof Error ? value.message : String(value); }
